using BlazorDX.Components;

namespace BlazorDX.Demo.Client.Docs;

/// <summary>One documented component: identity, blurb, where its live demo lives, and
/// the type name used to reflect its parameter reference.</summary>
/// <param name="Slug">URL segment, e.g. "datagrid" → /docs/datagrid.</param>
/// <param name="Name">Display name (may include a generic suffix).</param>
/// <param name="Category">Grouping for the sidebar.</param>
/// <param name="Summary">One-line description.</param>
/// <param name="DemoRoute">Route of the interactive demo.</param>
/// <param name="TypeName">Type name within BlazorDX.Components (with `1 for generics).</param>
public sealed record DocEntry(string Slug, string Name, string Category, string Summary, string DemoRoute, string TypeName);

/// <summary>
/// The single source of truth for the documentation site. The API reference for each
/// entry is generated by reflecting <see cref="ResolveType"/>; descriptions and demo
/// routes are curated here.
/// </summary>
public static class ComponentCatalog
{
    /// <summary>Categories in display order.</summary>
    public static readonly IReadOnlyList<string> Categories =
    [
        "Overlays & popups", "Selection & input", "Buttons & display", "Navigation & layout",
        "Data grids", "Data visualization", "Scheduling", "Editors, files & AI",
        "Feedback", "Barcodes & QR",
    ];

    public static readonly IReadOnlyList<DocEntry> Entries =
    [
        new("dialog", "DxDialog", "Overlays & popups", "Modal dialog: focus trap, scroll lock, Esc / click-outside dismiss, exit animation.", "/dialog", "DxDialog"),
        new("sheet", "DxSheet", "Overlays & popups", "Edge-anchored offcanvas panel (a DialogPrimitive that slides in).", "/overlays", "DxSheet"),
        new("popover", "DxPopover", "Overlays & popups", "Anchored popover with collision flip + viewport shift.", "/popover", "DxPopover"),
        new("tooltip", "DxTooltip", "Overlays & popups", "Hover/focus tooltip, anchored and flipping.", "/menu", "DxTooltip"),
        new("menu", "DxMenu", "Overlays & popups", "Click menu with roving-tabindex keyboard nav and ARIA menu roles.", "/menu", "DxMenu"),
        new("contextmenu", "DxContextMenu", "Overlays & popups", "Right-click menu positioned at the cursor.", "/overlays", "DxContextMenu"),
        new("commandpalette", "DxCommandPalette", "Overlays & popups", "⌘K palette: dialog + typeahead filter + run-on-Enter.", "/command", "DxCommandPalette"),
        new("keyboardshortcuts", "DxKeyboardShortcuts", "Overlays & popups", "Cheat-sheet overlay listing your DxHotkeys shortcuts (press ?).", "/hotkeys", "DxKeyboardShortcuts"),

        new("form", "DxForm<TModel>", "Selection & input", "Source-generated form: renders + validates a [DxFormModel], and the same descriptor projects to an AI tool (FormTool).", "/forms", "DxForm`1"),
        new("formsection", "DxFormSection", "Selection & input", "Labelled, collapsible field group (containerization within forms).", "/forms", "DxFormSection"),
        new("formgrid", "DxFormGrid", "Selection & input", "Responsive multi-column field layout.", "/forms", "DxFormGrid"),
        new("formfield", "DxFormField", "Selection & input", "Renders one form field by name for manual layout.", "/forms", "DxFormField"),
        new("select", "DxSelect<T>", "Selection & input", "Single-select dropdown composing positioning, dismiss, roving, and selection.", "/select", "DxSelect`1"),
        new("listbox", "DxListbox<T>", "Selection & input", "Inline single/multi list, two-way bound to a value set.", "/pickers", "DxListbox`1"),
        new("combobox", "DxComboBox<T>", "Selection & input", "Typeahead filter + dropdown (aria-activedescendant pattern).", "/pickers", "DxComboBox`1"),
        new("transferlist", "DxTransferList", "Selection & input", "Dual-listbox move-between, composed from two DxListbox.", "/transfer", "DxTransferList"),
        new("checkbox", "DxCheckbox", "Selection & input", "Native-backed boolean checkbox.", "/controls", "DxCheckbox"),
        new("switch", "DxSwitch", "Selection & input", "Native-backed toggle switch.", "/controls", "DxSwitch"),
        new("radiogroup", "DxRadioGroup<T>", "Selection & input", "Roving-tabindex radio group.", "/controls", "DxRadioGroup`1"),
        new("textbox", "DxTextBox", "Selection & input", "Text input (text/email/url/tel/search).", "/controls", "DxTextBox"),
        new("textarea", "DxTextArea", "Selection & input", "Multi-line text input.", "/controls", "DxTextArea"),
        new("password", "DxPassword", "Selection & input", "Password input with a reveal toggle.", "/controls", "DxPassword"),
        new("numeric", "DxNumeric<T>", "Selection & input", "Generic-math numeric input + stepper (INumber<T>).", "/controls", "DxNumeric`1"),
        new("rating", "DxRating", "Selection & input", "Star rating exposed as an ARIA slider.", "/rating", "DxRating"),
        new("datepicker", "DxDatePicker", "Selection & input", "Calendar popover with 2-D keyboard navigation.", "/layout", "DxDatePicker"),
        new("timepicker", "DxTimePicker", "Selection & input", "Time input backed by the native time picker.", "/pickers", "DxTimePicker"),
        new("daterangepicker", "DxDateRangePicker", "Selection & input", "Start/end range composing two DatePickers.", "/pickers", "DxDateRangePicker"),
        new("colorpicker", "DxColorPicker", "Selection & input", "Native color input with hex readout and preset swatches.", "/controls", "DxColorPicker"),
        new("maskedtextbox", "DxMaskedTextBox", "Selection & input", "Text input that formats against a mask.", "/controls", "DxMaskedTextBox"),
        new("rangeslider", "DxRangeSlider", "Selection & input", "Dual-thumb range slider, clamped so thumbs never cross.", "/controls", "DxRangeSlider"),
        new("fileupload", "DxFileUpload", "Selection & input", "Drag-drop upload zone over the native InputFile.", "/controls", "DxFileUpload"),
        new("virtualkeyboard", "DxVirtualKeyboard", "Selection & input", "On-screen QWERTY for touch/kiosk/a11y text entry.", "/keyboard", "DxVirtualKeyboard"),

        new("button", "DxButton", "Buttons & display", "Styled button with attribute splatting.", "/elements", "DxButton"),
        new("buttongroup", "DxButtonGroup", "Buttons & display", "Segmented group of adjacent buttons.", "/elements", "DxButtonGroup"),
        new("toolbar", "DxToolbar", "Buttons & display", "Horizontal toolbar container (role=toolbar).", "/elements", "DxToolbar"),
        new("splitbutton", "DxSplitButton", "Buttons & display", "Primary action + a caret menu (composes DxMenu).", "/elements", "DxSplitButton"),
        new("badge", "DxBadge", "Buttons & display", "Status pill or count badge; six variants + a dot.", "/elements", "DxBadge"),
        new("kbd", "DxKbd", "Buttons & display", "Renders a shortcut as styled <kbd> key caps.", "/hotkeys", "DxKbd"),
        new("chip", "DxChip", "Buttons & display", "Compact tag, optionally dismissible.", "/elements", "DxChip"),
        new("avatar", "DxAvatar", "Buttons & display", "Circular avatar — image or initials fallback.", "/elements", "DxAvatar"),
        new("card", "DxCard", "Buttons & display", "Surface container with optional header/footer.", "/elements", "DxCard"),
        new("slider", "DxSlider", "Buttons & display", "Numeric slider backed by a native range input.", "/elements", "DxSlider"),

        new("tabs", "DxTabs", "Navigation & layout", "Roving-tabindex tabs with automatic activation.", "/layout", "DxTabs"),
        new("accordion", "DxAccordion", "Navigation & layout", "Single/multi expand using selection state.", "/layout", "DxAccordion"),
        new("breadcrumbs", "DxBreadcrumbs", "Navigation & layout", "Navigation trail; last item is aria-current.", "/structure", "DxBreadcrumbs"),
        new("divider", "DxDivider", "Navigation & layout", "Separator with an optional centered label.", "/structure", "DxDivider"),
        new("drawer", "DxDrawer", "Navigation & layout", "Persistent push-layout side panel (non-modal).", "/structure", "DxDrawer"),
        new("timeline", "DxTimeline", "Navigation & layout", "Vertical event timeline with variant markers.", "/structure", "DxTimeline"),
        new("carousel", "DxCarousel", "Navigation & layout", "Keyboard-navigable slide rotator.", "/structure", "DxCarousel"),
        new("pager", "DxPager", "Navigation & layout", "Pagination with windowed page numbers.", "/paging", "DxPager"),
        new("stepper", "DxStepper", "Navigation & layout", "Wizard / multi-step flow.", "/wizard", "DxStepper"),
        new("tilelayout", "DxTileLayout", "Navigation & layout", "Reorderable dashboard tiles (drag + keyboard).", "/tiles", "DxTileLayout"),
        new("kanban", "DxKanban", "Navigation & layout", "Board of draggable cards across columns.", "/kanban", "DxKanban"),
        new("sortablelist", "DxSortableList", "Navigation & layout", "Drag/keyboard reorderable list.", "/sortable", "DxSortableList"),
        new("virtualize", "DxVirtualize<T>", "Navigation & layout", "Generalized windowing — only visible items in the DOM.", "/virtualize", "DxVirtualize`1"),
        new("treeview", "DxTreeView", "Navigation & layout", "Hierarchical tree with expand/collapse + keyboard nav.", "/structure", "DxTreeView"),
        new("splitter", "DxSplitter", "Navigation & layout", "Two resizable panes with a draggable divider.", "/structure", "DxSplitter"),
        new("themeprovider", "DxThemeProvider", "Navigation & layout", "Token theming (light/dark + accent) for a subtree.", "/theme", "DxThemeProvider"),

        new("datagrid", "DxDataGrid<TRow>", "Data grids", "Virtualized grid: sort/filter/group/aggregate/select/edit/reorder/resize/pin, in-memory or server-side.", "/grid", "DxDataGrid`1"),
        new("treegrid", "DxTreeGrid<TRow>", "Data grids", "Hierarchical tree-table; flattened + virtualized.", "/tree", "DxTreeGrid`1"),
        new("pivotgrid", "DxPivotGrid<TRow>", "Data grids", "Cross-tab reusing the Rust aggregation kernels.", "/pivot", "DxPivotGrid`1"),

        new("linechart", "DxLineChart", "Data visualization", "Series line chart, LTTB-downsampled by Rust/wasm.", "/charts", "DxLineChart"),
        new("areachart", "DxAreaChart", "Data visualization", "Filled series chart, Rust-downsampled.", "/charts", "DxAreaChart"),
        new("barchart", "DxBarChart", "Data visualization", "Categorical bar chart (vertical/horizontal).", "/charts", "DxBarChart"),
        new("piechart", "DxPieChart", "Data visualization", "Pie / donut with legend.", "/charts", "DxPieChart"),
        new("histogram", "DxHistogram", "Data visualization", "Bins values via the Rust histogram kernel.", "/charts", "DxHistogram"),
        new("sparkline", "DxSparkline", "Data visualization", "Inline line/bar trend, no axes.", "/charts", "DxSparkline"),
        new("radialgauge", "DxRadialGauge", "Data visualization", "270° arc meter gauge.", "/charts", "DxRadialGauge"),
        new("lineargauge", "DxLinearGauge", "Data visualization", "Zoned bar meter gauge.", "/charts", "DxLinearGauge"),
        new("scatterchart", "DxScatterChart", "Data visualization", "XY scatter plot.", "/charts", "DxScatterChart"),
        new("stackedbarchart", "DxStackedBarChart", "Data visualization", "Stacked or grouped series bars.", "/charts", "DxStackedBarChart"),
        new("radarchart", "DxRadarChart", "Data visualization", "Spider chart over shared axes.", "/charts", "DxRadarChart"),
        new("funnelchart", "DxFunnelChart", "Data visualization", "Stacked-trapezoid conversion funnel.", "/charts", "DxFunnelChart"),
        new("candlestickchart", "DxCandlestickChart", "Data visualization", "OHLC candlesticks coloured by direction.", "/charts", "DxCandlestickChart"),
        new("waterfallchart", "DxWaterfallChart", "Data visualization", "Running-total bars with total resets and connectors.", "/charts", "DxWaterfallChart"),
        new("bubblechart", "DxBubbleChart", "Data visualization", "Scatter plot with a third dimension encoded as radius.", "/charts", "DxBubbleChart"),
        new("heatmap", "DxHeatmap", "Data visualization", "Row x column grid, intensity via fill-opacity.", "/charts", "DxHeatmap"),
        new("bulletchart", "DxBulletChart", "Data visualization", "KPI vs. target vs. qualitative range bands.", "/charts", "DxBulletChart"),
        new("treemap", "DxTreemap", "Data visualization", "Squarified nested rectangles sized by value.", "/charts", "DxTreemap"),
        new("sunburst", "DxSunburst", "Data visualization", "Radial treemap; every node is its own ring.", "/charts", "DxSunburst"),
        new("boxplot", "DxBoxPlot", "Data visualization", "Q1/median/Q3 box, whiskers, outliers, optional violin.", "/charts", "DxBoxPlot"),
        new("sankeychart", "DxSankeyChart", "Data visualization", "Layered flow diagram with thickness-scaled ribbons.", "/charts", "DxSankeyChart"),
        new("networkgraph", "DxNetworkGraph", "Data visualization", "Force-directed graph; connected nodes cluster.", "/charts", "DxNetworkGraph"),
        new("parallelcoordinates", "DxParallelCoordinates", "Data visualization", "One axis per dimension, rows as crossing polylines.", "/charts", "DxParallelCoordinates"),
        new("wordcloud", "DxWordCloud", "Data visualization", "Spiral-packed words sized by weight.", "/charts", "DxWordCloud"),
        new("chorddiagram", "DxChordDiagram", "Data visualization", "Nodes as arcs, ribbons connecting flow slices.", "/charts", "DxChordDiagram"),

        new("calendar", "DxCalendar", "Scheduling", "Inline month calendar with single/range selection, markers, and a day template.", "/calendar", "DxCalendar"),
        new("scheduler", "DxScheduler", "Scheduling", "Week/Month/Day calendar with recurrence and drag-to-move/create.", "/scheduler", "DxScheduler"),
        new("gantt", "DxGantt", "Scheduling", "Task timeline bars with progress fills.", "/gantt", "DxGantt"),

        new("markdown", "DxMarkdown", "Editors, files & AI", "Safe Markdown renderer (encode-then-format).", "/markdown", "DxMarkdown"),
        new("markdowneditor", "DxMarkdownEditor", "Editors, files & AI", "Live split Markdown editor.", "/markdown", "DxMarkdownEditor"),
        new("richtexteditor", "DxRichTextEditor", "Editors, files & AI", "WYSIWYG over contentEditable, routed through an injected sanitizer.", "/richtext", "DxRichTextEditor"),
        new("chat", "DxChat", "Editors, files & AI", "AI chat surface; assistant turns render via DxMarkdown.", "/chat", "DxChat"),
        new("filemanager", "DxFileManager", "Editors, files & AI", "Two-pane folder tree + contents with a breadcrumb.", "/files", "DxFileManager"),
        new("querybuilder", "DxQueryBuilder", "Editors, files & AI", "Visual, nestable predicate tree (AND/OR groups).", "/query", "DxQueryBuilder"),
        new("imageeditor", "DxImageEditor", "Editors, files & AI", "Canvas image editor: adjust, filter, rotate/flip, export — via a TS bridge.", "/imageeditor", "DxImageEditor"),
        new("documentviewer", "DxDocumentViewer", "Editors, files & AI", "Multi-format viewer: images, Markdown, text/code, and native PDF.", "/docviewer", "DxDocumentViewer"),

        new("toasthost", "DxToastHost", "Feedback", "Scoped toast notifications (with ToastService).", "/feedback", "DxToastHost"),
        new("alert", "DxAlert", "Feedback", "Inline alert with severities; role=alert for errors.", "/feedback", "DxAlert"),
        new("spinner", "DxSpinner", "Feedback", "Loading spinner (role=status).", "/feedback", "DxSpinner"),
        new("progress", "DxProgress", "Feedback", "Determinate / indeterminate progress bar.", "/feedback", "DxProgress"),
        new("skeleton", "DxSkeleton", "Feedback", "Shimmer placeholder.", "/feedback", "DxSkeleton"),
        new("errorboundary", "DxErrorBoundary", "Feedback", "Contains a thrown exception; shows a retryable fallback and reports to IDxDiagnostics.", "/errors", "DxErrorBoundary"),

        new("qrcode", "DxQrCode", "Barcodes & QR", "QR code (versions 1–4, all EC levels), verified against published vectors.", "/barcodes", "DxQrCode"),
        new("barcode", "DxBarcode", "Barcodes & QR", "Code 128 (Set B) with an independent decoder round-trip.", "/barcodes", "DxBarcode"),
        new("ean13", "DxEan13", "Barcodes & QR", "EAN-13 retail barcode with computed check digit.", "/barcodes", "DxEan13"),
    ];

    // Curated usage examples, keyed by slug. Components without an entry fall back to
    // the reflected API table + the live demo link.
    private static readonly Dictionary<string, string> Examples = new(StringComparer.OrdinalIgnoreCase)
    {
        ["datagrid"] = """
            <DxDataGrid TRow="Person" Items="people" Accessor="accessor"
                        Selectable="true" Filterable="true" ShowExport="true"
                        KeyboardNavigation="true" />

            @code {
                // [GridRow] on Person → PersonGridAccessor is source-generated.
                private readonly PersonGridAccessor accessor = new();
                private IReadOnlyList<Person> people = Person.Load();
            }
            """,
        ["treegrid"] = """
            <DxTreeGrid TRow="Node" Items="roots" Accessor="accessor"
                        ChildrenSelector="@(n => n.Children)" InitiallyExpanded="true" />
            """,
        ["pivotgrid"] = """
            @using BlazorDX.Compute

            <DxPivotGrid TRow="Sale" Items="sales" Accessor="accessor"
                         RowField="0" ColumnField="1" ValueField="2"
                         Aggregate="GridAggregateKind.Sum" />
            """,
        ["dialog"] = """
            <button @onclick="() => open = true">Delete…</button>

            <DxDialog @bind-Open="open" AriaLabel="Confirm delete">
                <h2>Delete project?</h2>
                <button @onclick="() => open = false">Cancel</button>
            </DxDialog>

            @code { private bool open; }
            """,
        ["popover"] = """
            <DxPopover @bind-Open="open" Side="bottom" Align="start">
                <Trigger><button>Details</button></Trigger>
                <ChildContent>Follows the trigger; flips near edges.</ChildContent>
            </DxPopover>
            """,
        ["menu"] = """
            @using BlazorDX.Primitives.Overlays

            <DxMenu @bind-Open="open" Items="items">
                <Trigger><button>Actions ▾</button></Trigger>
            </DxMenu>

            @code {
                private bool open;
                private IReadOnlyList<MenuItem> items =
                    [new("Rename", () => {}), new("Delete", () => {})];
            }
            """,
        ["commandpalette"] = """
            @using BlazorDX.Primitives.Overlays

            <DxCommandPalette @bind-Open="open" Commands="commands" />

            @code {
                private bool open;
                private IReadOnlyList<Command> commands = [new("New file", () => {}, "File")];
            }
            """,
        ["kbd"] = """
            Press <DxKbd Combo="Ctrl+K" /> to search, <DxKbd Combo="Cmd+Shift+P" /> for commands.
            """,
        ["keyboardshortcuts"] = """
            <DxHotkeys Bindings="keys" />
            <DxKeyboardShortcuts Bindings="keys" @bind-Open="showKeys" />

            @code {
                private bool showKeys;
                private IReadOnlyList<Hotkey> keys =>
                [
                    new("Ctrl+K", EventCallback.Factory.Create(this, Search), "Search"),
                    new("?", EventCallback.Factory.Create(this, () => showKeys = true), "Show shortcuts"),
                ];
            }
            """,
        ["virtualkeyboard"] = """
            <input value="@text" readonly />
            <DxVirtualKeyboard @bind-Value="text" OnEnter="Submit" />

            @code { private string text = ""; }
            """,
        ["select"] = """
            @using BlazorDX.Primitives.Overlays

            <DxSelect TValue="string" Items="cities" @bind-Value="city" Placeholder="Choose…" />

            @code {
                private string? city;
                private IReadOnlyList<ListOption<string>> cities =
                    [new("ATX", "Austin"), new("BER", "Berlin")];
            }
            """,
        ["combobox"] = """
            <DxComboBox TValue="string" Items="cities" @bind-Value="city" Placeholder="Type a city…" />
            """,
        ["checkbox"] = """
            <DxCheckbox @bind-Value="notify" Label="Email me about updates" />
            <DxSwitch @bind-Value="dark" Label="Dark mode" />
            """,
        ["radiogroup"] = """
            <DxRadioGroup TValue="string" Items="plans" @bind-Value="plan" AriaLabel="Plan" />
            """,
        ["textbox"] = """
            <DxTextBox @bind-Value="name" Label="Full name" Immediate="true" />
            <DxTextArea @bind-Value="notes" Label="Notes" Rows="3" />
            """,
        ["numeric"] = """
            <DxNumeric TValue="int" @bind-Value="seats" Label="Seats" Min="1" Max="50" />
            <DxNumeric TValue="decimal" @bind-Value="price" Step="0.5m" Format="F2" />
            """,
        ["datepicker"] = """
            <DxDatePicker @bind-Value="date" />

            @code { private DateOnly? date; }
            """,
        ["daterangepicker"] = """
            <DxDateRangePicker @bind-Start="start" @bind-End="end" />
            """,
        ["button"] = """
            <DxButton Variant="primary" Text="Save" OnClick="OnSave" />
            <DxButton Variant="ghost" Disabled="true">Cancel</DxButton>
            """,
        ["splitbutton"] = """
            @using BlazorDX.Primitives.Overlays

            <DxSplitButton Text="Save" OnClick="OnSave" Items="items" />

            @code {
                private IReadOnlyList<MenuItem> items =
                    [new("Save as draft", () => {}), new("Save a copy", () => {})];
            }
            """,
        ["tabs"] = """
            @using BlazorDX.Primitives.Navigation

            <DxTabs Items="tabs" @bind-SelectedIndex="tab" />

            @code {
                private int tab;
                private IReadOnlyList<TabItem> tabs = [new("Overview", Body), new("Specs", Body)];
                private static RenderFragment Body => @<p>Panel content.</p>;
            }
            """,
        ["pager"] = """
            <DxPager TotalItems="247" PageSize="10" @bind-Page="page" />

            @code { private int page = 1; }
            """,
        ["kanban"] = """
            <DxKanban Columns="columns" OnChange="StateHasChanged" />

            @code {
                private IReadOnlyList<KanbanColumn> columns =
                    [new("To do", new[] { new KanbanCard("Task A") }), new("Done")];
            }
            """,
        ["toasthost"] = """
            @inject ToastService Toasts

            <button @onclick='() => Toasts.Show("Saved!", "success")'>Save</button>
            <DxToastHost />
            """,
        ["alert"] = """
            <DxAlert Severity="success" Title="Deployed">Your site is live.</DxAlert>
            <DxAlert Severity="error" Title="Build failed" Dismissible="true" />
            """,
        ["barchart"] = """
            <DxBarChart Points="bars" />

            @code {
                private IReadOnlyList<ChartPoint> bars = [new(Category: "Mon", Y: 12), new(Category: "Tue", Y: 18)];
            }
            """,
        ["qrcode"] = """
            @using BlazorDX.Primitives.Barcodes.Qr

            <DxQrCode Value="https://anthropic.com" Level="QrErrorLevel.Medium" />
            """,
        ["fileupload"] = """
            <DxFileUpload Accept="image/*,.pdf" OnFilesSelected="OnFiles" />
            """,
        ["rangeslider"] = """
            <DxRangeSlider @bind-Low="low" @bind-High="high" Min="0" Max="1000" Step="50" ShowValue="true" />
            """,
        ["treeview"] = """
            <DxTreeView Items="roots" @bind-Selected="node" InitiallyExpanded="true" />

            @code {
                private IReadOnlyList<TreeNode> roots = [new("src", new List<TreeNode> { new("App.cs") })];
            }
            """,
        ["splitter"] = """
            <DxSplitter InitialSize="240">
                <First>Navigator</First>
                <Second>Editor</Second>
            </DxSplitter>
            """,
    };

    /// <summary>A curated usage example for a slug, or empty if none is provided.</summary>
    public static string ExampleFor(string slug) =>
        Examples.TryGetValue(slug, out string? code) ? code : string.Empty;

    public static DocEntry? Find(string slug) =>
        Entries.FirstOrDefault(e => string.Equals(e.Slug, slug, StringComparison.OrdinalIgnoreCase));

    public static IEnumerable<DocEntry> InCategory(string category) =>
        Entries.Where(e => e.Category == category);

    /// <summary>Resolves the component type for the reflected API table.</summary>
    public static Type? ResolveType(DocEntry entry) =>
        typeof(DxButton).Assembly.GetType($"BlazorDX.Components.{entry.TypeName}");
}
