using System.Security.Cryptography;
using System.Text;
using BlazorDX.Conduit;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;

namespace BlazorDX.Demo;

/// <summary>
/// DEMO-ONLY broker for the "/ai-chat" example app's ephemeral AI chat messages.
///
/// This is <b>not</b> part of <c>BlazorDX.Conduit</c>'s real contract. The Conduit itself never
/// encrypts anything — it is a blind, zero-knowledge router (see
/// <c>docs/adr/0016-zero-trust-ephemeral-chat-conduit.md</c> and
/// <c>McpProxyEndpoint</c>'s own doc comment: "this server never parses, inspects, or decrypts
/// it"). In a real deployment, the encrypted handshake response that
/// <c>SecureEphemeralChat</c>'s <c>EstablishSession</c> delegate receives comes from an actual
/// external MCP resource-provider server holding its own keypair, reached over whatever
/// transport ADR 0016 documents. This class stands in for that external provider purely so the
/// "/ai-chat" demo page can show a full, real client-side handshake — real P-256 ECDH, real
/// AES-256-GCM, a real closed Shadow DOM mount — without requiring any external API key or a
/// second running process. Do not mistake this for production wiring: a real deployment also
/// registers an <see cref="IEphemeralSessionAuthorizer"/> before exposing anything like this
/// beyond a local demo (this endpoint, like <c>/mcp</c> and <c>/mcp-proxy</c> elsewhere in this
/// sample, is anonymous).
///
/// <see cref="System.Security.Cryptography"/>'s <c>ECDiffieHellman</c>/<c>AesGcm</c> types need a
/// native crypto backend that browser-wasm does not provide — exactly why the feature has its
/// own Rust/wasm crypto core client-side (<c>dx_security</c>). This broker's encryption logic
/// therefore must run here, server-side, and never in <c>BlazorDX.Demo.Client</c>.
/// </summary>
public static class DemoAiChatBroker
{
    /// <summary>
    /// <c>POST /demo/ai-chat/handshake</c> — the client's freshly wasm-generated P-256 public
    /// key comes in, an encrypted response encrypted for the shared secret with a fresh server
    /// keypair goes out. Request/response shapes are demo-local (<see cref="HandshakeRequest"/>
    /// / <see cref="HandshakeResponse"/>), not a BlazorDX.Conduit contract.
    /// </summary>
    public const string HandshakeRoute = "/demo/ai-chat/handshake";

    /// <summary>
    /// <c>POST /demo/ai-chat/withdraw/{sessionId}</c> — pushes a real "WITHDRAW" SSE event to
    /// the session via <see cref="EphemeralEventsEndpoint.PushEphemeralEventAsync"/>, exactly as
    /// a real external provider revoking a message would. Nothing about this push is simulated;
    /// only the fact that it is *this* demo page triggering it (rather than an external
    /// provider's own revoke action) is demo-specific.
    /// </summary>
    public const string WithdrawRoute = "/demo/ai-chat/withdraw/{sessionId}";

    private const int P256PublicKeyLength = 65; // 0x04 || X(32) || Y(32)
    private const int NonceLength = 12;
    private const int TagLength = 16;

    public static IEndpointRouteBuilder MapDemoAiChatBroker(this WebApplication app)
    {
        app.MapPost(HandshakeRoute, HandleHandshakeAsync).DisableAntiforgery();
        app.MapPost(WithdrawRoute, HandleWithdrawAsync).DisableAntiforgery();
        return app;
    }

    private static Task<IResult> HandleHandshakeAsync(HandshakeRequest request, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(request.SessionId) || string.IsNullOrWhiteSpace(request.ClientPublicKeyBase64))
        {
            return Task.FromResult(Results.BadRequest(new { error = "sessionId and clientPublicKeyBase64 are required." }));
        }

        byte[] clientKeyBytes;
        try
        {
            clientKeyBytes = Convert.FromBase64String(request.ClientPublicKeyBase64);
        }
        catch (FormatException)
        {
            return Task.FromResult(Results.BadRequest(new { error = "clientPublicKeyBase64 was not valid base64." }));
        }

        if (clientKeyBytes.Length != P256PublicKeyLength || clientKeyBytes[0] != 0x04)
        {
            return Task.FromResult(Results.BadRequest(
                new { error = "clientPublicKeyBase64 was not an uncompressed P-256 SEC1 key (0x04 || X(32) || Y(32))." }));
        }

        string replyText = string.IsNullOrEmpty(request.ReplyText)
            ? "(the demo did not supply a reply — nothing to say here.)"
            : request.ReplyText;

        // Import the client's REAL public key (sent to us over HTTP, generated by real
        // crypto.getRandomValues entropy inside the browser's wasm module) as a public-key-only
        // handle — no private scalar involved on this side. Skip the leading 0x04 tag byte.
        ECParameters clientParameters = new()
        {
            Curve = ECCurve.NamedCurves.nistP256,
            Q = new ECPoint
            {
                X = clientKeyBytes[1..33],
                Y = clientKeyBytes[33..65],
            },
        };

        using ECDiffieHellman clientPublicKey = ECDiffieHellman.Create(clientParameters);
        // A fresh server keypair, real randomness this time (no fixed seed — that trick is
        // EphemeralChatFixture-only, for a deterministic Playwright vector; this broker accepts
        // whatever real public key a real browser handshake sends it).
        using ECDiffieHellman server = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);

        byte[] nonce = RandomNumberGenerator.GetBytes(NonceLength);
        byte[] ciphertextWithTag;
        byte[] sharedSecret = server.DeriveRawSecretAgreement(clientPublicKey.PublicKey);
        try
        {
            byte[] plaintext = Encoding.UTF8.GetBytes(replyText);
            byte[] ciphertext = new byte[plaintext.Length];
            byte[] tag = new byte[TagLength];
            using (AesGcm gcm = new(sharedSecret, TagLength))
            {
                gcm.Encrypt(nonce, plaintext, ciphertext, tag);
            }

            // Trailing 16-byte tag concatenated onto the ciphertext, matching the convention
            // BlazorDX.Security.Rust's decrypt_payload (and the aes-gcm crate) expects.
            ciphertextWithTag = [.. ciphertext, .. tag];
        }
        finally
        {
            // Cheap, cost-free hygiene consistent with the feature's own zero-trust framing —
            // .NET gives no hard guarantee against a GC copy having already happened, unlike the
            // Rust side's `zeroize`, but there is no reason not to clear what we can.
            CryptographicOperations.ZeroMemory(sharedSecret);
        }

        ECParameters serverExported = server.ExportParameters(includePrivateParameters: false);
        byte[] serverPublicKeyBytes = [0x04, .. serverExported.Q.X!, .. serverExported.Q.Y!];

        var response = new HandshakeResponse
        {
            ServerPublicKeyBase64 = Convert.ToBase64String(serverPublicKeyBytes),
            NonceBase64 = Convert.ToBase64String(nonce),
            CiphertextBase64 = Convert.ToBase64String(ciphertextWithTag),
        };
        return Task.FromResult(Results.Json(response));
    }

    private static async Task<IResult> HandleWithdrawAsync(
        string sessionId, EphemeralSessionRegistry registry, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(sessionId))
        {
            return Results.BadRequest(new { error = "sessionId is required." });
        }

        // Real push through the real Conduit registry — the same method a production
        // McpBrokerClient/webhook relay would call. A session nobody is currently watching is a
        // silent no-op (the Conduit is an ephemeral relay, not a durable queue).
        await registry.PushEphemeralEventAsync(sessionId, "WITHDRAW", "{}", cancellationToken).ConfigureAwait(false);
        return Results.Accepted();
    }
}

/// <summary>Request body for <see cref="DemoAiChatBroker.HandshakeRoute"/>. Demo-local shape, not a BlazorDX.Conduit contract.</summary>
internal sealed class HandshakeRequest
{
    public string SessionId { get; set; } = string.Empty;

    public string ClientPublicKeyBase64 { get; set; } = string.Empty;

    /// <summary>The plaintext the caller wants this handshake's ciphertext to decrypt to — the demo's canned "AI reply".</summary>
    public string ReplyText { get; set; } = string.Empty;
}

/// <summary>Response body for <see cref="DemoAiChatBroker.HandshakeRoute"/>, shaped to match <c>BlazorDX.Components.EphemeralHandshakeResult</c> (camelCase JSON, via ASP.NET Core's default naming policy).</summary>
internal sealed class HandshakeResponse
{
    public string ServerPublicKeyBase64 { get; set; } = string.Empty;

    public string NonceBase64 { get; set; } = string.Empty;

    public string CiphertextBase64 { get; set; } = string.Empty;
}
