using BlazorDX.Components;
using BlazorDX.Compute;
using BlazorDX.Interop;
using BlazorDX.Primitives.Grid;
using Bunit;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace BlazorDX.Components.Tests;

/// <summary>A demo row type; the accessor is generated by BlazorDX.SourceGen.</summary>
[GridRow]
public sealed class WidgetRow
{
    [GridColumn("Name", Order = 0)]
    public string Name { get; set; } = string.Empty;

    [GridColumn("Quantity", Order = 1)]
    public int Quantity { get; set; }
}

/// <summary>
/// Renders the styled grid through bUnit. Exercises Tier 2 markup and, by
/// inheritance, the Tier 1 primitive's windowing — with the managed compute and
/// no-op DOM bridges standing in for the browser services.
/// </summary>
public sealed class DxDataGridTests : TestContext
{
    private static readonly List<WidgetRow> Rows =
    [
        new() { Name = "Alpha", Quantity = 10 },
        new() { Name = "Beta", Quantity = 20 },
        new() { Name = "Gamma", Quantity = 30 },
    ];

    public DxDataGridTests()
    {
        Services.AddScoped<IGridCompute, ManagedGridCompute>();
        Services.AddScoped<IGridDomInterop, NullGridDomInterop>();
    }

    [Fact]
    public void Renders_header_and_rows_with_grid_semantics()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor()));

        string markup = grid.Markup;
        Assert.Contains("role=\"grid\"", markup);
        Assert.Contains("Quantity", markup);   // generated column header
        Assert.Contains("Alpha", markup);       // generated cell text
        Assert.Contains("Gamma", markup);
    }

    [Fact]
    public void Reports_total_row_count_for_assistive_tech()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor()));

        Assert.Contains("aria-rowcount=\"3\"", grid.Markup);
    }

    private static readonly List<WidgetRow> Grouped =
    [
        new() { Name = "Alpha", Quantity = 1 },
        new() { Name = "Alpha", Quantity = 2 },
        new() { Name = "Beta", Quantity = 3 },
    ];

    [Fact]
    public void Grouping_renders_a_header_per_group_with_counts()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Grouped)
            .Add(g => g.Accessor, new WidgetRowGridAccessor())
            .Add(g => g.GroupByColumn, 0));

        Assert.Equal(2, grid.FindAll(".dx-grid-group").Count);   // Alpha, Beta
        Assert.Contains("Name: Alpha", grid.Markup);
        Assert.Contains("(2)", grid.Markup);                      // Alpha row count
    }

    [Fact]
    public void Collapsing_a_group_hides_its_data_rows()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Grouped)
            .Add(g => g.Accessor, new WidgetRowGridAccessor())
            .Add(g => g.GroupByColumn, 0));

        Assert.Equal(3, grid.FindAll(".dx-grid-row").Count);      // all rows expanded

        grid.FindAll(".dx-grid-group")[0].Click();                // collapse "Alpha"

        Assert.Single(grid.FindAll(".dx-grid-row"));              // only Beta's row remains
        Assert.Equal(2, grid.FindAll(".dx-grid-group").Count);    // both headers still shown
    }

    [Fact]
    public void Ctrl_arrow_right_reorders_columns_and_cells()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor()));

        Assert.Equal("Name", grid.FindAll(".dx-grid-th")[0].TextContent.Trim());

        grid.FindAll(".dx-grid-th")[0].KeyDown(new Microsoft.AspNetCore.Components.Web.KeyboardEventArgs
        {
            Key = "ArrowRight",
            CtrlKey = true,
        });

        // Header order swapped...
        Assert.Equal("Quantity", grid.FindAll(".dx-grid-th")[0].TextContent.Trim());
        Assert.Equal("Name", grid.FindAll(".dx-grid-th")[1].TextContent.Trim());
        // ...and the first data row's cells follow.
        var cells = grid.FindAll(".dx-grid-row")[0].QuerySelectorAll(".dx-grid-cell");
        Assert.Equal("10", cells[0].TextContent);   // Quantity now first (Alpha=10)
        Assert.Equal("Alpha", cells[1].TextContent);
    }

    [Fact]
    public void Dragging_a_header_onto_another_reorders_columns()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor()));

        grid.FindAll(".dx-grid-th")[0].TriggerEvent("ondragstart", new Microsoft.AspNetCore.Components.Web.DragEventArgs());
        grid.FindAll(".dx-grid-th")[1].TriggerEvent("ondrop", new Microsoft.AspNetCore.Components.Web.DragEventArgs());

        Assert.Equal("Quantity", grid.FindAll(".dx-grid-th")[0].TextContent.Trim());
    }

    [Fact]
    public void Selectable_renders_a_checkbox_per_row_plus_header()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor())
            .Add(g => g.Selectable, true));

        // One select-all in the header + one per visible row.
        Assert.Equal(4, grid.FindAll(".dx-grid-select").Count);
    }

    [Fact]
    public void Clicking_a_row_checkbox_selects_it_and_raises_event()
    {
        IReadOnlyList<WidgetRow>? selected = null;
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor())
            .Add(g => g.Selectable, true)
            .Add(g => g.SelectionChanged, rows => selected = rows));

        // The first .dx-grid-select is the header select-all; row checkboxes follow.
        grid.FindAll(".dx-grid-row .dx-grid-select")[0].Change(true);

        Assert.NotNull(selected);
        Assert.Single(selected!);
        Assert.Equal("Alpha", selected![0].Name);
        Assert.Contains("dx-grid-row-selected", grid.Find(".dx-grid-row").GetAttribute("class"));
        Assert.Equal("true", grid.Find(".dx-grid-row").GetAttribute("aria-selected"));
    }

    [Fact]
    public void Select_all_header_selects_every_row()
    {
        IReadOnlyList<WidgetRow>? selected = null;
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor())
            .Add(g => g.Selectable, true)
            .Add(g => g.SelectionChanged, rows => selected = rows));

        grid.Find(".dx-grid-header .dx-grid-select").Change(true);

        Assert.Equal(3, selected!.Count);
    }

    [Fact]
    public void Filterable_renders_an_input_per_column()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor())
            .Add(g => g.Filterable, true));

        Assert.Equal(2, grid.FindAll(".dx-grid-filter-input").Count);   // Name, Quantity
    }

    [Fact]
    public void Typing_a_filter_narrows_the_visible_rows()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor())
            .Add(g => g.Filterable, true));

        Assert.Equal(3, grid.FindAll(".dx-grid-row").Count);

        // Filter the Name column (first input) to "lph" -> only "Alpha".
        grid.FindAll(".dx-grid-filter-input")[0].Input("lph");

        Assert.Single(grid.FindAll(".dx-grid-row"));
        Assert.Contains("Alpha", grid.Find(".dx-grid-row").TextContent);
    }

    [Fact]
    public void Generated_accessor_reports_editable_columns_and_writes_back()
    {
        var accessor = new WidgetRowGridAccessor();
        Assert.True(accessor.CanEditColumn(0));   // Name (string)
        Assert.True(accessor.CanEditColumn(1));   // Quantity (int)
        Assert.False(accessor.CanEditColumn(9));  // out of range

        WidgetRow row = new() { Name = "Alpha", Quantity = 10 };
        accessor.SetCellText(row, 0, "Renamed");
        accessor.SetCellText(row, 1, "42");
        Assert.Equal("Renamed", row.Name);
        Assert.Equal(42, row.Quantity);

        // Unparseable numeric input leaves the value unchanged.
        accessor.SetCellText(row, 1, "not-a-number");
        Assert.Equal(42, row.Quantity);
    }

    [Fact]
    public void Double_click_opens_an_inline_editor_for_editable_cell()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, new List<WidgetRow> { new() { Name = "Alpha", Quantity = 10 } })
            .Add(g => g.Accessor, new WidgetRowGridAccessor())
            .Add(g => g.Editable, true));

        Assert.Empty(grid.FindAll(".dx-grid-edit-input"));

        grid.FindAll(".dx-grid-cell-editable")[0].TriggerEvent("ondblclick", new Microsoft.AspNetCore.Components.Web.MouseEventArgs());

        Assert.Single(grid.FindAll(".dx-grid-edit-input"));
    }

    [Fact]
    public void Editing_a_cell_and_pressing_enter_commits_through_the_accessor()
    {
        var rows = new List<WidgetRow> { new() { Name = "Alpha", Quantity = 10 } };
        WidgetRow? edited = null;
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor())
            .Add(g => g.Editable, true)
            .Add(g => g.RowEdited, r => edited = r));

        grid.FindAll(".dx-grid-cell-editable")[0].TriggerEvent("ondblclick", new Microsoft.AspNetCore.Components.Web.MouseEventArgs());

        var input = grid.Find(".dx-grid-edit-input");
        input.Input("Renamed");   // updates the draft
        input.KeyDown(new Microsoft.AspNetCore.Components.Web.KeyboardEventArgs { Key = "Enter" });

        Assert.Equal("Renamed", rows[0].Name);
        Assert.NotNull(edited);
        Assert.Empty(grid.FindAll(".dx-grid-edit-input"));   // editor closed
    }

    [Fact]
    public void Escape_cancels_the_edit_without_writing_back()
    {
        var rows = new List<WidgetRow> { new() { Name = "Alpha", Quantity = 10 } };
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor())
            .Add(g => g.Editable, true));

        grid.FindAll(".dx-grid-cell-editable")[0].TriggerEvent("ondblclick", new Microsoft.AspNetCore.Components.Web.MouseEventArgs());
        var input = grid.Find(".dx-grid-edit-input");
        input.Input("Renamed");
        input.KeyDown(new Microsoft.AspNetCore.Components.Web.KeyboardEventArgs { Key = "Escape" });

        Assert.Equal("Alpha", rows[0].Name);                 // unchanged
        Assert.Empty(grid.FindAll(".dx-grid-edit-input"));   // editor closed
    }

    [Fact]
    public void Cells_are_not_editable_unless_editable_is_set()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, new List<WidgetRow> { new() { Name = "Alpha", Quantity = 10 } })
            .Add(g => g.Accessor, new WidgetRowGridAccessor()));

        Assert.Empty(grid.FindAll(".dx-grid-cell-editable"));
    }

    [Fact]
    public void Each_header_has_a_resize_handle()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor()));

        Assert.Equal(2, grid.FindAll(".dx-grid-resize").Count);   // Name, Quantity
    }

    [Fact]
    public void Dragging_the_resize_handle_sets_an_explicit_column_width()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor()));

        // No overlay until a resize starts.
        Assert.Empty(grid.FindAll(".dx-grid-resize-overlay"));

        // Start on the first column's handle, then move +70px (150 default + 70 = 220).
        grid.FindAll(".dx-grid-resize")[0].TriggerEvent("onpointerdown",
            new Microsoft.AspNetCore.Components.Web.PointerEventArgs { ClientX = 100 });
        Assert.Single(grid.FindAll(".dx-grid-resize-overlay"));   // overlay captures the drag

        grid.Find(".dx-grid-resize-overlay").TriggerEvent("onpointermove",
            new Microsoft.AspNetCore.Components.Web.PointerEventArgs { ClientX = 170 });

        string headerStyle = grid.Find(".dx-grid-header").GetAttribute("style")!;
        Assert.Contains("220px", headerStyle);

        // Releasing ends the gesture and removes the overlay.
        grid.Find(".dx-grid-resize-overlay").TriggerEvent("onpointerup",
            new Microsoft.AspNetCore.Components.Web.PointerEventArgs { ClientX = 170 });
        Assert.Empty(grid.FindAll(".dx-grid-resize-overlay"));

        // The width persists after the gesture.
        Assert.Contains("220px", grid.Find(".dx-grid-header").GetAttribute("style")!);
    }

    [Fact]
    public void Resize_clamps_to_a_minimum_width()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor()));

        grid.FindAll(".dx-grid-resize")[0].TriggerEvent("onpointerdown",
            new Microsoft.AspNetCore.Components.Web.PointerEventArgs { ClientX = 100 });
        // Drag far left (would be negative width) -> clamps to the 60px minimum.
        grid.Find(".dx-grid-resize-overlay").TriggerEvent("onpointermove",
            new Microsoft.AspNetCore.Components.Web.PointerEventArgs { ClientX = -500 });

        Assert.Contains("60px", grid.Find(".dx-grid-header").GetAttribute("style")!);
    }

    [Fact]
    public void Pinned_columns_get_sticky_positioning_with_cumulative_offsets()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor())
            .Add(g => g.PinnedColumns, 1));

        Assert.Contains("dx-grid-pinnable", grid.Find(".dx-grid").GetAttribute("class"));

        // First header column is pinned at left:0 with the edge-divider class.
        var firstTh = grid.FindAll(".dx-grid-th")[0];
        Assert.Contains("dx-grid-pin-edge", firstTh.GetAttribute("class")!);
        Assert.Contains("position:sticky", firstTh.GetAttribute("style")!);
        Assert.Contains("left:0", firstTh.GetAttribute("style")!);

        // The second (unpinned) column is not sticky.
        Assert.DoesNotContain("dx-grid-pinned", grid.FindAll(".dx-grid-th")[1].GetAttribute("class")!);
    }

    [Fact]
    public void Pinned_offset_accounts_for_the_selection_column()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor())
            .Add(g => g.Selectable, true)
            .Add(g => g.PinnedColumns, 1));

        // Selection cell pins at left:0; the first data column pins after it (36px).
        var headerSelect = grid.Find(".dx-grid-header .dx-grid-select-cell");
        Assert.Contains("left:0", headerSelect.GetAttribute("style")!);

        var firstTh = grid.FindAll(".dx-grid-th").First(e => !e.ClassList.Contains("dx-grid-select-cell"));
        Assert.Contains("left:36px", firstTh.GetAttribute("style")!);
    }

    [Fact]
    public void No_pinning_leaves_cells_unstyled()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Rows)
            .Add(g => g.Accessor, new WidgetRowGridAccessor()));

        Assert.DoesNotContain("dx-grid-pinnable", grid.Find(".dx-grid").GetAttribute("class"));
        Assert.Empty(grid.FindAll(".dx-grid-pinned"));
    }

    [Fact]
    public void Group_headers_show_per_group_subtotals()
    {
        IRenderedComponent<DxDataGrid<WidgetRow>> grid = RenderComponent<DxDataGrid<WidgetRow>>(parameters => parameters
            .Add(g => g.Items, Grouped)
            .Add(g => g.Accessor, new WidgetRowGridAccessor())
            .Add(g => g.GroupByColumn, 0)
            .Add(g => g.Aggregations, new Dictionary<int, GridAggregateKind> { [1] = GridAggregateKind.Sum }));

        // Alpha group: Quantity 1 + 2 = 3.
        string summary = grid.Find(".dx-grid-group .dx-grid-group-summary").TextContent;
        Assert.Contains("Quantity", summary);
        Assert.Contains("3", summary);
    }
}
