using BlazorDX.Components;
using BlazorDX.Interop;
using BlazorDX.Primitives.Grid;
using Bunit;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace BlazorDX.Components.Tests;

/// <summary>A demo hierarchical node; the accessor is generated by BlazorDX.SourceGen.</summary>
[GridRow]
public sealed class TreeWidget
{
    [GridColumn("Name", Order = 0)]
    public string Name { get; set; } = string.Empty;

    [GridColumn("Kind", Order = 1)]
    public string Kind { get; set; } = string.Empty;

    public IReadOnlyList<TreeWidget> Kids { get; init; } = [];
}

/// <summary>Hierarchy flattening, expand/collapse, and ARIA for the tree grid.</summary>
public sealed class DxTreeGridTests : TestContext
{
    public DxTreeGridTests()
    {
        Services.AddScoped<IGridDomInterop, NullGridDomInterop>();
    }

    private static IReadOnlyList<TreeWidget> Tree() =>
    [
        new TreeWidget
        {
            Name = "A", Kind = "folder",
            Kids = [new() { Name = "A1", Kind = "file" }, new() { Name = "A2", Kind = "file" }],
        },
        new TreeWidget { Name = "B", Kind = "file" },
    ];

    private IRenderedComponent<DxTreeGrid<TreeWidget>> Render(bool expanded = false) =>
        RenderComponent<DxTreeGrid<TreeWidget>>(parameters => parameters
            .Add(t => t.Items, Tree())
            .Add(t => t.Accessor, new TreeWidgetGridAccessor())
            .Add(t => t.ChildrenSelector, n => n.Kids)
            .Add(t => t.InitiallyExpanded, expanded));

    [Fact]
    public void Collapsed_by_default_shows_only_roots()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render();

        Assert.Equal("treegrid", tree.Find("[role=treegrid]").GetAttribute("role"));
        Assert.Equal(2, tree.FindAll(".dx-grid-row").Count);   // A, B
        Assert.DoesNotContain("A1", tree.Markup);
    }

    [Fact]
    public void Initially_expanded_flattens_the_whole_tree()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render(expanded: true);

        Assert.Equal(4, tree.FindAll(".dx-grid-row").Count);   // A, A1, A2, B
        Assert.Contains("A1", tree.Markup);
    }

    [Fact]
    public void Clicking_the_twisty_expands_a_node()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render();
        Assert.Equal(2, tree.FindAll(".dx-grid-row").Count);

        tree.FindAll(".dx-tree-toggle")[0].Click();   // expand "A"

        Assert.Equal(4, tree.FindAll(".dx-grid-row").Count);
        Assert.Equal("true", tree.FindAll(".dx-grid-row")[0].GetAttribute("aria-expanded"));
    }

    [Fact]
    public void Leaf_rows_have_no_twisty_and_parents_do()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render();

        // Two roots: "A" (parent -> toggle) and "B" (leaf -> spacer).
        Assert.Single(tree.FindAll(".dx-tree-toggle"));
        Assert.Single(tree.FindAll(".dx-tree-spacer"));
    }

    [Fact]
    public void Aria_level_reflects_depth()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render(expanded: true);

        var rows = tree.FindAll(".dx-grid-row");
        Assert.Equal("1", rows[0].GetAttribute("aria-level"));   // A (root)
        Assert.Equal("2", rows[1].GetAttribute("aria-level"));   // A1 (child)
    }

    [Fact]
    public void Container_is_the_single_tab_stop_with_a_roving_active_row()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render();

        var container = tree.Find("[role=treegrid]");
        Assert.Equal("0", container.GetAttribute("tabindex"));
        Assert.Empty(tree.FindAll(".dx-grid-row[tabindex]"));   // rows aren't independent tab stops
        Assert.NotNull(container.GetAttribute("aria-activedescendant"));

        // The active row (defaults to the first) carries the id aria-activedescendant points at.
        var activeRow = tree.FindAll(".dx-grid-row")[0];
        Assert.Equal(container.GetAttribute("aria-activedescendant"), activeRow.GetAttribute("id"));
        Assert.Contains("dx-grid-row-active", activeRow.ClassName);
    }

    [Fact]
    public void Arrow_right_expands_the_active_parent_row()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render();

        tree.Find("[role=treegrid]").KeyDown(new KeyboardEventArgs { Key = "ArrowRight" });

        Assert.Equal(4, tree.FindAll(".dx-grid-row").Count);
    }

    [Fact]
    public void Arrow_right_on_an_expanded_row_descends_to_its_first_child()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render(expanded: true);
        var container = tree.Find("[role=treegrid]");

        container.KeyDown(new KeyboardEventArgs { Key = "ArrowRight" });   // A -> A1

        Assert.Equal("A1", tree.FindAll(".dx-tree-label")[1].TextContent);
        Assert.Contains("dx-grid-row-active", tree.FindAll(".dx-grid-row")[1].ClassName);
    }

    [Fact]
    public void Arrow_down_then_up_moves_the_active_row_across_the_flattened_list()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render(expanded: true);   // A, A1, A2, B
        var container = tree.Find("[role=treegrid]");

        container.KeyDown(new KeyboardEventArgs { Key = "ArrowDown" });   // A -> A1
        container.KeyDown(new KeyboardEventArgs { Key = "ArrowDown" });   // A1 -> A2
        Assert.Contains("dx-grid-row-active", tree.FindAll(".dx-grid-row")[2].ClassName);

        container.KeyDown(new KeyboardEventArgs { Key = "ArrowUp" });     // A2 -> A1
        Assert.Contains("dx-grid-row-active", tree.FindAll(".dx-grid-row")[1].ClassName);
    }

    [Fact]
    public void Arrow_left_on_a_leaf_moves_to_its_parent()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render(expanded: true);   // A, A1, A2, B
        var container = tree.Find("[role=treegrid]");

        container.KeyDown(new KeyboardEventArgs { Key = "ArrowDown" });   // A -> A1 (a leaf)
        container.KeyDown(new KeyboardEventArgs { Key = "ArrowLeft" });   // A1 -> A (its parent)

        Assert.Contains("dx-grid-row-active", tree.FindAll(".dx-grid-row")[0].ClassName);
    }

    [Fact]
    public void Home_and_end_jump_to_the_first_and_last_row()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render(expanded: true);   // A, A1, A2, B
        var container = tree.Find("[role=treegrid]");

        container.KeyDown(new KeyboardEventArgs { Key = "End" });
        Assert.Contains("dx-grid-row-active", tree.FindAll(".dx-grid-row")[3].ClassName);

        container.KeyDown(new KeyboardEventArgs { Key = "Home" });
        Assert.Contains("dx-grid-row-active", tree.FindAll(".dx-grid-row")[0].ClassName);
    }

    [Fact]
    public void Clicking_a_row_makes_it_the_active_row()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render(expanded: true);   // A, A1, A2, B

        tree.FindAll(".dx-grid-row")[2].Click();   // A2

        Assert.Contains("dx-grid-row-active", tree.FindAll(".dx-grid-row")[2].ClassName);
        Assert.DoesNotContain("dx-grid-row-active", tree.FindAll(".dx-grid-row")[0].ClassName);
    }

    [Fact]
    public void Collapsing_the_active_rows_ancestor_re_anchors_the_active_index()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render(expanded: true);   // A, A1, A2, B
        var container = tree.Find("[role=treegrid]");

        container.KeyDown(new KeyboardEventArgs { Key = "ArrowDown" });   // A -> A1 (active)
        tree.FindAll(".dx-tree-toggle")[0].Click();                      // collapse "A" away

        // A1 no longer exists in the flattened list; the active index must land on a real row.
        Assert.Equal(2, tree.FindAll(".dx-grid-row").Count);   // A, B
        Assert.Single(tree.FindAll(".dx-grid-row-active"));
    }
}
