using BlazorDX.Components;
using BlazorDX.Interop;
using BlazorDX.Primitives.Grid;
using Bunit;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace BlazorDX.Components.Tests;

/// <summary>A demo hierarchical node; the accessor is generated by BlazorDX.SourceGen.</summary>
[GridRow]
public sealed class TreeWidget
{
    [GridColumn("Name", Order = 0)]
    public string Name { get; set; } = string.Empty;

    [GridColumn("Kind", Order = 1)]
    public string Kind { get; set; } = string.Empty;

    public IReadOnlyList<TreeWidget> Kids { get; init; } = [];
}

/// <summary>Hierarchy flattening, expand/collapse, and ARIA for the tree grid.</summary>
public sealed class DxTreeGridTests : TestContext
{
    public DxTreeGridTests()
    {
        Services.AddScoped<IGridDomInterop, NullGridDomInterop>();
    }

    private static IReadOnlyList<TreeWidget> Tree() =>
    [
        new TreeWidget
        {
            Name = "A", Kind = "folder",
            Kids = [new() { Name = "A1", Kind = "file" }, new() { Name = "A2", Kind = "file" }],
        },
        new TreeWidget { Name = "B", Kind = "file" },
    ];

    private IRenderedComponent<DxTreeGrid<TreeWidget>> Render(bool expanded = false) =>
        RenderComponent<DxTreeGrid<TreeWidget>>(parameters => parameters
            .Add(t => t.Items, Tree())
            .Add(t => t.Accessor, new TreeWidgetGridAccessor())
            .Add(t => t.ChildrenSelector, n => n.Kids)
            .Add(t => t.InitiallyExpanded, expanded));

    [Fact]
    public void Collapsed_by_default_shows_only_roots()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render();

        Assert.Equal("treegrid", tree.Find("[role=treegrid]").GetAttribute("role"));
        Assert.Equal(2, tree.FindAll(".dx-grid-row").Count);   // A, B
        Assert.DoesNotContain("A1", tree.Markup);
    }

    [Fact]
    public void Initially_expanded_flattens_the_whole_tree()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render(expanded: true);

        Assert.Equal(4, tree.FindAll(".dx-grid-row").Count);   // A, A1, A2, B
        Assert.Contains("A1", tree.Markup);
    }

    [Fact]
    public void Clicking_the_twisty_expands_a_node()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render();
        Assert.Equal(2, tree.FindAll(".dx-grid-row").Count);

        tree.FindAll(".dx-tree-toggle")[0].Click();   // expand "A"

        Assert.Equal(4, tree.FindAll(".dx-grid-row").Count);
        Assert.Equal("true", tree.FindAll(".dx-grid-row")[0].GetAttribute("aria-expanded"));
    }

    [Fact]
    public void Leaf_rows_have_no_twisty_and_parents_do()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render();

        // Two roots: "A" (parent -> toggle) and "B" (leaf -> spacer).
        Assert.Single(tree.FindAll(".dx-tree-toggle"));
        Assert.Single(tree.FindAll(".dx-tree-spacer"));
    }

    [Fact]
    public void Aria_level_reflects_depth()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render(expanded: true);

        var rows = tree.FindAll(".dx-grid-row");
        Assert.Equal("1", rows[0].GetAttribute("aria-level"));   // A (root)
        Assert.Equal("2", rows[1].GetAttribute("aria-level"));   // A1 (child)
    }

    [Fact]
    public void Arrow_right_expands_a_focused_parent_row()
    {
        IRenderedComponent<DxTreeGrid<TreeWidget>> tree = Render();

        tree.FindAll(".dx-grid-row")[0].KeyDown(new KeyboardEventArgs { Key = "ArrowRight" });

        Assert.Equal(4, tree.FindAll(".dx-grid-row").Count);
    }
}
