using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BlazorDX.SourceGen;

/// <summary>
/// Emits a reflection-free <c>ToChartPoints()</c> extension for every type annotated with
/// <c>[ChartRow]</c>, projecting each row into one <c>ChartPoint</c> from its
/// <c>[ChartValue]</c>-tagged properties. So a chart binds existing domain data
/// (<c>rows.ToChartPoints()</c>) without a hand-written mapping step and with zero runtime
/// reflection — the same story <c>[GridRow]</c> already tells for the DataGrid.
/// </summary>
[Generator]
public sealed class ChartAccessorGenerator : IIncrementalGenerator
{
    private const string RowAttribute = "BlazorDX.Components.ChartRowAttribute";
    private const string ChartPointFqn = "global::BlazorDX.Components.ChartPoint";

    // ChartPoint's declared parameter order — emitted in this order purely for readability of the
    // generated source; named arguments make the actual order immaterial to the compiler.
    private static readonly string[] FieldOrder =
        { "X", "Y", "Category", "Y2", "Y3", "Y4", "Series", "Color" };

    private static readonly HashSet<string> TextFields = new(StringComparer.Ordinal) { "Category", "Series", "Color" };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<ChartRowModel> models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                RowAttribute,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) => ChartRowAnalysis.Build((INamedTypeSymbol)ctx.TargetSymbol));

        context.RegisterSourceOutput(models, static (production, model) =>
            production.AddSource($"{model.TypeName}ChartExtensions.g.cs", Emit(model)));
    }

    private static SourceText Emit(ChartRowModel model)
    {
        StringBuilder source = new();
        source.AppendLine("// <auto-generated/> by BlazorDX.SourceGen");
        source.AppendLine("#nullable enable");
        source.AppendLine();

        bool hasNamespace = model.Namespace is not null;
        if (hasNamespace)
        {
            source.AppendLine($"namespace {model.Namespace};");
            source.AppendLine();
        }

        string extensionName = $"{model.TypeName}ChartExtensions";
        source.AppendLine($"{model.Accessibility} static class {extensionName}");
        source.AppendLine("{");
        source.AppendLine(
            $"    public static global::System.Collections.Generic.IReadOnlyList<{ChartPointFqn}> ToChartPoints(" +
            $"this global::System.Collections.Generic.IEnumerable<{model.TypeName}> rows)");
        source.AppendLine("    {");
        source.AppendLine($"        var __points = new global::System.Collections.Generic.List<{ChartPointFqn}>();");
        source.AppendLine($"        foreach ({model.TypeName} __row in rows)");
        source.AppendLine("        {");
        source.AppendLine($"            __points.Add(new {ChartPointFqn}({BuildArguments(model)}));");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        return __points;");
        source.AppendLine("    }");
        source.AppendLine("}");

        return SourceText.From(source.ToString(), Encoding.UTF8);
    }

    // Only the fields a [ChartValue] property actually maps become constructor arguments; every
    // other field is simply omitted, falling back to ChartPoint's own default.
    private static string BuildArguments(ChartRowModel model)
    {
        Dictionary<string, string> propertyByField = new(StringComparer.Ordinal);
        foreach (ChartFieldMapping mapping in model.Mappings)
        {
            propertyByField[mapping.Field] = mapping.PropertyName;
        }

        List<string> arguments = new();
        foreach (string field in FieldOrder)
        {
            if (!propertyByField.TryGetValue(field, out string? property))
            {
                continue;
            }

            string expression = TextFields.Contains(field)
                ? $"global::System.Convert.ToString(__row.{property}, global::System.Globalization.CultureInfo.InvariantCulture)"
                : $"global::System.Convert.ToDouble(__row.{property}, global::System.Globalization.CultureInfo.InvariantCulture)";

            arguments.Add($"{field}: {expression}");
        }

        return string.Join(", ", arguments);
    }
}
