using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BlazorDX.SourceGen;

/// <summary>
/// Emits a reflection-free <c>IFormModel&lt;TModel&gt;</c> for every type annotated
/// with <c>[DxFormModel]</c>: the field metadata, typed get/set, and validation a
/// <c>DxForm</c> renders, and that <c>FormTool</c> projects into an AI tool. Generated,
/// so the form layer stays trim- and Native-AOT-safe.
/// </summary>
[Generator]
public sealed class FormModelGenerator : IIncrementalGenerator
{
    private const string ModelAttribute = "BlazorDX.Primitives.Forms.DxFormModelAttribute";
    private const string Ns = "global::BlazorDX.Primitives.Forms";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<(FormModelDef Model, ImmutableArray<Diagnostic> Diagnostics)> models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ModelAttribute,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) =>
                    FormModelAnalysis.Build((INamedTypeSymbol)ctx.TargetSymbol, ctx.Attributes[0]));

        context.RegisterSourceOutput(models, static (production, result) =>
        {
            foreach (Diagnostic diagnostic in result.Diagnostics)
            {
                production.ReportDiagnostic(diagnostic);
            }

            production.AddSource($"{result.Model.TypeName}FormModel.g.cs", Emit(result.Model));
        });

        // DX2006 (nesting/array cycles) needs the whole compilation's set of models,
        // not one type's field list -- a second, independent output driven by a
        // .Collect() of the same provider. This doesn't disturb per-type incremental
        // caching above: that RegisterSourceOutput is still driven by the
        // uncollected `models` provider.
        IncrementalValueProvider<ImmutableArray<FormModelDef>> allModels =
            models.Select(static (r, _) => r.Model).Collect();
        context.RegisterSourceOutput(allModels, static (production, all) =>
        {
            foreach (Diagnostic diagnostic in FormModelCycles.Validate(all))
            {
                production.ReportDiagnostic(diagnostic);
            }
        });
    }

    private static SourceText Emit(FormModelDef model)
    {
        StringBuilder s = new();
        s.AppendLine("// <auto-generated/> by BlazorDX.SourceGen");
        s.AppendLine("#nullable enable");
        s.AppendLine();
        if (model.Namespace is not null)
        {
            s.AppendLine($"namespace {model.Namespace};");
            s.AppendLine();
        }

        string name = $"{model.TypeName}FormModel";
        s.AppendLine($"{model.Accessibility} sealed class {name} : {Ns}.IFormModel<{model.TypeName}>");
        s.AppendLine("{");

        EmitTool(s, model);
        EmitFields(s, model);
        EmitGetString(s, model);
        EmitSetString(s, model);
        EmitValidate(s, model);
        EmitUntypedWrappers(s, model);

        if (model.Fields.Any(f => f.Kind == "Object"))
        {
            EmitNestedAccessors(s, model);
        }

        if (model.Fields.Any(f => f.Kind == "Array"))
        {
            EmitArrayAccessors(s, model);
        }

        s.AppendLine("}");
        return SourceText.From(s.ToString(), Encoding.UTF8);
    }

    private static void EmitTool(StringBuilder s, FormModelDef model)
    {
        s.AppendLine($"    public string ToolName => {Literal(model.ToolName)};");
        s.AppendLine($"    public string? ToolDescription => {Literal(model.ToolDescription)};");
        s.AppendLine();
    }

    private static void EmitFields(StringBuilder s, FormModelDef model)
    {
        s.AppendLine($"    private static readonly {Ns}.FormFieldInfo[] _fields = new {Ns}.FormFieldInfo[]");
        s.AppendLine("    {");
        foreach (FormFieldDef f in model.Fields)
        {
            string choices = f.Choices.IsDefaultOrEmpty
                ? "null"
                : "new string[] { " + string.Join(", ", f.Choices.Select(Literal)) + " }";
            s.AppendLine(
                $"        new {Ns}.FormFieldInfo({Literal(f.PropertyName)}, {Literal(f.Label)}, {Literal(f.Description)}, " +
                $"{Ns}.FormFieldKind.{f.Kind}, {Bool(f.Required)}, {NDouble(f.Min)}, {NDouble(f.Max)}, " +
                $"{NInt(f.MaxLength)}, {Literal(f.Pattern)}, {Literal(f.Placeholder)}, {choices}, {Bool(f.Sensitive)}, " +
                $"{Literal(f.DependsOn)}, {Literal(f.DependsOnValue)}, {Ns}.FormFieldDependsOnOperator.{f.DependsOnOperator}, " +
                $"{NType(f.NestedTypeFqn)}, {NKind(f.ArrayElementKind)}),");
        }

        s.AppendLine("    };");
        s.AppendLine();
        s.AppendLine($"    public global::System.Collections.Generic.IReadOnlyList<{Ns}.FormFieldInfo> Fields => _fields;");
        s.AppendLine();
    }

    private static void EmitGetString(StringBuilder s, FormModelDef model)
    {
        s.AppendLine($"    public string GetString({model.TypeName} model, string field) => field switch");
        s.AppendLine("    {");
        foreach (FormFieldDef f in model.Fields)
        {
            // Object/Array fields have no scalar string form -- deliberately excluded
            // rather than left to fall through the default arm below, since that
            // arm's placement must not be mistaken for handling them.
            if (f.Kind is "Object" or "Array")
            {
                continue;
            }

            if (f.Kind == "Date")
            {
                // ISO yyyy-MM-dd so the value binds straight into a native date input.
                string body = f.IsNullableValue
                    ? $"(model.{f.PropertyName} is {{}} __d_{f.PropertyName} ? __d_{f.PropertyName}.ToString(\"yyyy-MM-dd\", global::System.Globalization.CultureInfo.InvariantCulture) : string.Empty)"
                    : $"model.{f.PropertyName}.ToString(\"yyyy-MM-dd\", global::System.Globalization.CultureInfo.InvariantCulture)";
                s.AppendLine($"        {Literal(f.PropertyName)} => {body},");
                continue;
            }

            s.AppendLine(
                $"        {Literal(f.PropertyName)} => global::System.Convert.ToString(model.{f.PropertyName}, " +
                "global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty,");
        }

        s.AppendLine("        _ => string.Empty,");
        s.AppendLine("    };");
        s.AppendLine();
    }

    private static void EmitSetString(StringBuilder s, FormModelDef model)
    {
        s.AppendLine($"    public void SetString({model.TypeName} model, string field, string value)");
        s.AppendLine("    {");
        s.AppendLine("        switch (field)");
        s.AppendLine("        {");
        foreach (FormFieldDef f in model.Fields)
        {
            if (f.Kind is "Object" or "Array")
            {
                continue;
            }

            s.AppendLine($"            case {Literal(f.PropertyName)}:");
            s.Append(SetBody(f));
            s.AppendLine("                break;");
        }

        s.AppendLine("            default: break;");
        s.AppendLine("        }");
        s.AppendLine("    }");
        s.AppendLine();
    }

    private static string SetBody(FormFieldDef f)
    {
        string v = "__v_" + f.PropertyName;
        if (f.IsString)
        {
            return $"                model.{f.PropertyName} = value;\n";
        }

        return f.Kind switch
        {
            "Bool" =>
                $"                if (global::System.Boolean.TryParse(value, out var {v})) model.{f.PropertyName} = {v};\n",
            "Integer" or "Number" =>
                $"                if ({f.UnderlyingFqn}.TryParse(value, global::System.Globalization.NumberStyles.Any, " +
                $"global::System.Globalization.CultureInfo.InvariantCulture, out var {v})) model.{f.PropertyName} = {v};\n",
            "Date" =>
                $"                if ({f.UnderlyingFqn}.TryParse(value, global::System.Globalization.CultureInfo.InvariantCulture, " +
                $"global::System.Globalization.DateTimeStyles.None, out var {v})) model.{f.PropertyName} = {v};\n",
            "Enum" =>
                $"                if (global::System.Enum.TryParse<{f.UnderlyingFqn}>(value, true, out var {v})) model.{f.PropertyName} = {v};\n",
            _ =>
                $"                model.{f.PropertyName} = value;\n",
        };
    }

    private static void EmitValidate(StringBuilder s, FormModelDef model)
    {
        s.AppendLine(
            $"    public global::System.Collections.Generic.IReadOnlyList<{Ns}.FormValidationError> Validate({model.TypeName} model)");
        s.AppendLine("    {");
        s.AppendLine($"        var errors = new global::System.Collections.Generic.List<{Ns}.FormValidationError>();");
        foreach (FormFieldDef f in model.Fields)
        {
            if (f.Kind == "Object")
            {
                // DX2007 guarantees an Object field's DependsOn is always null by the
                // time Emit runs (Build strips a violating field's DependsOn), so no
                // IsActive wrapper is ever needed here.
                EmitNestedFieldValidation(s, f);
                continue;
            }

            if (f.Kind == "Array")
            {
                EmitArrayFieldValidation(s, f);
                continue;
            }

            if (f.DependsOn is null)
            {
                EmitFieldChecks(s, f);
                continue;
            }

            // Conditional field: its constraints (Required included) only apply while
            // FormFieldActivity.IsActive holds — the same evaluator DxForm's renderer,
            // DxFormField, and FormTool.ApplyArguments all call, so there is exactly one
            // implementation of "is this field currently active."
            s.AppendLine(
                $"        if ({Ns}.FormFieldActivity.IsActive(this, model, {Literal(f.DependsOn)}, " +
                $"{Literal(f.DependsOnValue)}, {Ns}.FormFieldDependsOnOperator.{f.DependsOnOperator}))");
            s.AppendLine("        {");
            EmitFieldChecks(s, f);
            s.AppendLine("        }");
        }

        if (model.Validatable)
        {
            // The model implements IValidatableObject: run its cross-field validation too,
            // mapping each ValidationResult to a per-field (or form-level) error.
            s.AppendLine(
                "        var __ctx = new global::System.ComponentModel.DataAnnotations.ValidationContext(model);");
            s.AppendLine(
                "        foreach (var __vr in ((global::System.ComponentModel.DataAnnotations.IValidatableObject)model).Validate(__ctx))");
            s.AppendLine("        {");
            s.AppendLine("            string __member = string.Empty;");
            s.AppendLine("            foreach (var __n in __vr.MemberNames) { __member = __n; break; }");
            s.AppendLine(
                $"            errors.Add(new {Ns}.FormValidationError(__member, __vr.ErrorMessage ?? string.Empty));");
            s.AppendLine("        }");
        }

        s.AppendLine("        return errors;");
        s.AppendLine("    }");
    }

    private static void EmitFieldChecks(StringBuilder s, FormFieldDef f)
    {
        string prop = $"model.{f.PropertyName}";
        string err(string msg) => $"            errors.Add(new {Ns}.FormValidationError({Literal(f.PropertyName)}, {Literal(msg)}));";

        if (f.Required)
        {
            if (f.IsString)
            {
                s.AppendLine($"        if (string.IsNullOrWhiteSpace({prop}))");
                s.AppendLine(err($"{f.Label} is required."));
            }
            else if (f.IsNullableValue)
            {
                s.AppendLine($"        if (!{prop}.HasValue)");
                s.AppendLine(err($"{f.Label} is required."));
            }
        }

        if (f.MaxLength is { } maxLen && f.IsString)
        {
            s.AppendLine($"        if ({prop} != null && {prop}.Length > {maxLen})");
            s.AppendLine(err($"{f.Label} must be {maxLen} characters or fewer."));
        }

        if (!string.IsNullOrEmpty(f.Pattern) && f.IsString)
        {
            s.AppendLine(
                $"        if (!string.IsNullOrEmpty({prop}) && !global::System.Text.RegularExpressions.Regex.IsMatch({prop}, {Literal(f.Pattern)}))");
            s.AppendLine(err($"{f.Label} is not in the expected format."));
        }

        if (f.Kind is "Integer" or "Number")
        {
            string access = f.IsNullableValue ? $"{prop}.Value" : prop;
            string guard = f.IsNullableValue ? $"{prop}.HasValue && " : string.Empty;
            if (f.Min is { } min)
            {
                s.AppendLine($"        if ({guard}{access} < {Num(min)})");
                s.AppendLine(err($"{f.Label} must be at least {Trim(min)}."));
            }

            if (f.Max is { } max)
            {
                s.AppendLine($"        if ({guard}{access} > {Num(max)})");
                s.AppendLine(err($"{f.Label} must be at most {Trim(max)}."));
            }
        }
    }

    // Validates an Object-kind field: required-when-null, else recurse into the
    // nested descriptor's own Validate and re-prefix each error's field path.
    private static void EmitNestedFieldValidation(StringBuilder s, FormFieldDef f)
    {
        // Captured into a local rather than repeating "model.{Prop}" across the
        // null-check and the else branch: nullable-flow narrowing of a LOCAL is
        // unambiguously reliable, where narrowing a property re-accessed through its
        // getter is a subtler case not worth relying on here (this repo builds with
        // TreatWarningsAsErrors, so a possible-null-argument warning is a build break).
        string local = $"__nested_{f.PropertyName}";
        s.AppendLine($"        var {local} = model.{f.PropertyName};");
        s.AppendLine($"        if ({local} is null)");
        s.AppendLine("        {");
        if (f.Required)
        {
            s.AppendLine(
                $"            errors.Add(new {Ns}.FormValidationError({Literal(f.PropertyName)}, {Literal($"{f.Label} is required.")}));");
        }

        s.AppendLine("        }");
        s.AppendLine("        else");
        s.AppendLine("        {");
        s.AppendLine($"            foreach (var __e in new {f.NestedDescriptorFqn}().Validate({local}))");
        s.AppendLine("            {");
        s.AppendLine($"                errors.Add(new {Ns}.FormValidationError($\"{f.PropertyName}.{{__e.Field}}\", __e.Message));");
        s.AppendLine("            }");
        s.AppendLine("        }");
    }

    // Validates an Array-kind field. List-level Required ("at least one item") for
    // both flavors; array-of-nested additionally recurses per-element with an
    // indexed field path. Array-of-scalar per-item constraint checks are a stated v1
    // scope cut (see ADR 0019) -- not emitted here.
    private static void EmitArrayFieldValidation(StringBuilder s, FormFieldDef f)
    {
        string prop = $"model.{f.PropertyName}";
        if (f.Required)
        {
            s.AppendLine($"        if ({prop}.Count == 0)");
            s.AppendLine(
                $"            errors.Add(new {Ns}.FormValidationError({Literal(f.PropertyName)}, {Literal($"{f.Label} must have at least one item.")}));");
        }

        if (f.NestedTypeFqn is not null)
        {
            s.AppendLine($"        for (int __i = 0; __i < {prop}.Count; __i++)");
            s.AppendLine("        {");
            s.AppendLine($"            foreach (var __e in new {f.NestedDescriptorFqn}().Validate({prop}[__i]))");
            s.AppendLine("            {");
            s.AppendLine($"                errors.Add(new {Ns}.FormValidationError($\"{f.PropertyName}[{{__i}}].{{__e.Field}}\", __e.Message));");
            s.AppendLine("            }");
            s.AppendLine("        }");
        }
    }

    // The object-typed IFormModelUntyped members: GetString/SetString/Validate all
    // have a non-default body on that interface (only the nested/array members do),
    // so every generated model -- even a scalar-only one -- must implement these
    // three as thin casts onto its own typed members.
    private static void EmitUntypedWrappers(StringBuilder s, FormModelDef model)
    {
        s.AppendLine($"    public string GetString(object model, string field) => GetString(({model.TypeName})model, field);");
        s.AppendLine($"    public void SetString(object model, string field, string value) => SetString(({model.TypeName})model, field, value);");
        s.AppendLine(
            $"    public global::System.Collections.Generic.IReadOnlyList<{Ns}.FormValidationError> Validate(object model) => Validate(({model.TypeName})model);");
        s.AppendLine();
    }

    // GetNestedInstance/SetNestedInstance/GetNestedDescriptor -- only emitted when
    // the model has >= 1 Object field.
    private static void EmitNestedAccessors(StringBuilder s, FormModelDef model)
    {
        FormFieldDef[] fields = model.Fields.Where(f => f.Kind == "Object").ToArray();

        s.AppendLine("    public object? GetNestedInstance(object model, string field)");
        s.AppendLine("    {");
        s.AppendLine($"        var __m = ({model.TypeName})model;");
        s.AppendLine("        return field switch");
        s.AppendLine("        {");
        foreach (FormFieldDef f in fields)
        {
            s.AppendLine($"            {Literal(f.PropertyName)} => __m.{f.PropertyName},");
        }

        s.AppendLine("            _ => null,");
        s.AppendLine("        };");
        s.AppendLine("    }");
        s.AppendLine();

        s.AppendLine("    public void SetNestedInstance(object model, string field, object? instance)");
        s.AppendLine("    {");
        s.AppendLine($"        var __m = ({model.TypeName})model;");
        s.AppendLine("        switch (field)");
        s.AppendLine("        {");
        foreach (FormFieldDef f in fields)
        {
            s.AppendLine($"            case {Literal(f.PropertyName)}: __m.{f.PropertyName} = ({f.NestedTypeFqn})instance!; break;");
        }

        s.AppendLine("        }");
        s.AppendLine("    }");
        s.AppendLine();

        s.AppendLine($"    public {Ns}.IFormModelUntyped? GetNestedDescriptor(string field) => field switch");
        s.AppendLine("    {");
        foreach (FormFieldDef f in fields)
        {
            s.AppendLine($"        {Literal(f.PropertyName)} => new {f.NestedDescriptorFqn}(),");
        }

        s.AppendLine("        _ => null,");
        s.AppendLine("    };");
        s.AppendLine();

        s.AppendLine("    public object NewNestedInstance(string field) => field switch");
        s.AppendLine("    {");
        foreach (FormFieldDef f in fields)
        {
            s.AppendLine($"        {Literal(f.PropertyName)} => new {f.NestedTypeFqn}(),");
        }

        s.AppendLine("        _ => throw new global::System.NotSupportedException(),");
        s.AppendLine("    };");
        s.AppendLine();
    }

    // GetArrayStrings/SetArrayStrings (array-of-scalar), GetArrayInstances/
    // SetArrayInstances/GetArrayElementDescriptor (array-of-nested), and
    // NewArrayElement (both flavors) -- only emitted when the model has >= 1 Array
    // field. Every accessor uses a plain foreach loop rather than LINQ extension
    // syntax, since the generated file adds no "using System.Linq;".
    private static void EmitArrayAccessors(StringBuilder s, FormModelDef model)
    {
        FormFieldDef[] arrayFields = model.Fields.Where(f => f.Kind == "Array").ToArray();
        FormFieldDef[] scalarArrays = arrayFields.Where(f => f.ArrayElementKind is not null).ToArray();
        FormFieldDef[] nestedArrays = arrayFields.Where(f => f.NestedTypeFqn is not null).ToArray();

        s.AppendLine("    public global::System.Collections.Generic.IReadOnlyList<string> GetArrayStrings(object model, string field)");
        s.AppendLine("    {");
        s.AppendLine($"        var __m = ({model.TypeName})model;");
        s.AppendLine("        switch (field)");
        s.AppendLine("        {");
        foreach (FormFieldDef f in scalarArrays)
        {
            s.AppendLine($"            case {Literal(f.PropertyName)}:");
            s.AppendLine("            {");
            s.AppendLine("                var __result = new global::System.Collections.Generic.List<string>();");
            s.AppendLine($"                foreach (var __x in __m.{f.PropertyName}) {{ __result.Add({ArrayElementToString(f, "__x")}); }}");
            s.AppendLine("                return __result;");
            s.AppendLine("            }");
        }

        s.AppendLine("        }");
        s.AppendLine("        return global::System.Array.Empty<string>();");
        s.AppendLine("    }");
        s.AppendLine();

        s.AppendLine("    public void SetArrayStrings(object model, string field, global::System.Collections.Generic.IReadOnlyList<string> items)");
        s.AppendLine("    {");
        s.AppendLine($"        var __m = ({model.TypeName})model;");
        s.AppendLine("        switch (field)");
        s.AppendLine("        {");
        foreach (FormFieldDef f in scalarArrays)
        {
            s.AppendLine($"            case {Literal(f.PropertyName)}:");
            s.AppendLine("            {");
            s.AppendLine($"                var __list = new global::System.Collections.Generic.List<{f.UnderlyingFqn}>();");
            s.AppendLine("                foreach (var __s in items)");
            s.AppendLine("                {");
            s.Append(ArrayElementFromString(f));
            s.AppendLine("                }");
            s.AppendLine($"                __m.{f.PropertyName} = __list;");
            s.AppendLine("                break;");
            s.AppendLine("            }");
        }

        s.AppendLine("        }");
        s.AppendLine("    }");
        s.AppendLine();

        s.AppendLine("    public global::System.Collections.Generic.IReadOnlyList<object> GetArrayInstances(object model, string field)");
        s.AppendLine("    {");
        s.AppendLine($"        var __m = ({model.TypeName})model;");
        s.AppendLine("        switch (field)");
        s.AppendLine("        {");
        foreach (FormFieldDef f in nestedArrays)
        {
            s.AppendLine($"            case {Literal(f.PropertyName)}:");
            s.AppendLine("            {");
            s.AppendLine("                var __result = new global::System.Collections.Generic.List<object>();");
            s.AppendLine($"                foreach (var __x in __m.{f.PropertyName}) {{ __result.Add(__x!); }}");
            s.AppendLine("                return __result;");
            s.AppendLine("            }");
        }

        s.AppendLine("        }");
        s.AppendLine("        return global::System.Array.Empty<object>();");
        s.AppendLine("    }");
        s.AppendLine();

        s.AppendLine("    public void SetArrayInstances(object model, string field, global::System.Collections.Generic.IReadOnlyList<object> items)");
        s.AppendLine("    {");
        s.AppendLine($"        var __m = ({model.TypeName})model;");
        s.AppendLine("        switch (field)");
        s.AppendLine("        {");
        foreach (FormFieldDef f in nestedArrays)
        {
            s.AppendLine($"            case {Literal(f.PropertyName)}:");
            s.AppendLine("            {");
            s.AppendLine($"                var __list = new global::System.Collections.Generic.List<{f.NestedTypeFqn}>();");
            s.AppendLine($"                foreach (var __x in items) {{ __list.Add(({f.NestedTypeFqn})__x); }}");
            s.AppendLine($"                __m.{f.PropertyName} = __list;");
            s.AppendLine("                break;");
            s.AppendLine("            }");
        }

        s.AppendLine("        }");
        s.AppendLine("    }");
        s.AppendLine();

        s.AppendLine($"    public {Ns}.IFormModelUntyped? GetArrayElementDescriptor(string field) => field switch");
        s.AppendLine("    {");
        foreach (FormFieldDef f in nestedArrays)
        {
            s.AppendLine($"        {Literal(f.PropertyName)} => new {f.NestedDescriptorFqn}(),");
        }

        s.AppendLine("        _ => null,");
        s.AppendLine("    };");
        s.AppendLine();

        s.AppendLine("    public object NewArrayElement(string field) => field switch");
        s.AppendLine("    {");
        foreach (FormFieldDef f in nestedArrays)
        {
            s.AppendLine($"        {Literal(f.PropertyName)} => new {f.NestedTypeFqn}(),");
        }

        foreach (FormFieldDef f in scalarArrays)
        {
            s.AppendLine($"        {Literal(f.PropertyName)} => (object){ScalarDefaultLiteral(f)},");
        }

        s.AppendLine("        _ => throw new global::System.NotSupportedException(),");
        s.AppendLine("    };");
        s.AppendLine();
    }

    // The per-element invariant-string conversion for an array-of-scalar field,
    // mirroring EmitGetString's per-field conversion (Date needs explicit
    // yyyy-MM-dd formatting; everything else round-trips through Convert.ToString).
    private static string ArrayElementToString(FormFieldDef f, string itemExpr) => f.ArrayElementKind == "Date"
        ? $"{itemExpr}.ToString(\"yyyy-MM-dd\", global::System.Globalization.CultureInfo.InvariantCulture)"
        : $"(global::System.Convert.ToString({itemExpr}, global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty)";

    // The per-element parse-and-add statement for an array-of-scalar field, mirroring
    // SetBody's per-field parse logic. A malformed element is silently skipped (not
    // added) -- "bad input is ignored," the same posture SetBody already has for a
    // single scalar field.
    private static string ArrayElementFromString(FormFieldDef f) => f.ArrayElementKind switch
    {
        "Bool" => "                    if (global::System.Boolean.TryParse(__s, out var __v)) __list.Add(__v);\n",
        "Integer" or "Number" =>
            $"                    if ({f.UnderlyingFqn}.TryParse(__s, global::System.Globalization.NumberStyles.Any, " +
            "global::System.Globalization.CultureInfo.InvariantCulture, out var __v)) __list.Add(__v);\n",
        "Date" =>
            $"                    if ({f.UnderlyingFqn}.TryParse(__s, global::System.Globalization.CultureInfo.InvariantCulture, " +
            "global::System.Globalization.DateTimeStyles.None, out var __v)) __list.Add(__v);\n",
        "Enum" => $"                    if (global::System.Enum.TryParse<{f.UnderlyingFqn}>(__s, true, out var __v)) __list.Add(__v);\n",
        _ => "                    __list.Add(__s);\n",
    };

    // The blank default an array-of-scalar's "add row" starts from, matching each
    // Kind's own invariant-string empty form.
    private static string ScalarDefaultLiteral(FormFieldDef f) => f.ArrayElementKind switch
    {
        "Integer" or "Number" => "\"0\"",
        "Bool" => "\"False\"",
        "Enum" => f.Choices.IsDefaultOrEmpty ? "\"\"" : Literal(f.Choices[0]),
        _ => "\"\"",
    };

    private static string NType(string? nestedTypeFqn) => nestedTypeFqn is null ? "null" : $"typeof({nestedTypeFqn})";

    private static string NKind(string? kind) => kind is null ? "null" : $"{Ns}.FormFieldKind.{kind}";

    // ---- literal helpers ----

    private static string Literal(string? value) =>
        value is null ? "null" : SymbolDisplay.FormatLiteral(value, quote: true);

    private static string Bool(bool value) => value ? "true" : "false";

    private static string NDouble(double? value) =>
        value is { } d ? $"(double?){Num(d)}" : "(double?)null";

    private static string NInt(int? value) =>
        value is { } i ? $"(int?){i.ToString(CultureInfo.InvariantCulture)}" : "(int?)null";

    private static string Num(double value) =>
        value.ToString("R", CultureInfo.InvariantCulture);

    private static string Trim(double value) =>
        value.ToString("0.######", CultureInfo.InvariantCulture);
}
