using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BlazorDX.SourceGen;

/// <summary>
/// Emits a reflection-free <c>IFormModel&lt;TModel&gt;</c> for every type annotated
/// with <c>[DxFormModel]</c>: the field metadata, typed get/set, and validation a
/// <c>DxForm</c> renders, and that <c>FormTool</c> projects into an AI tool. Generated,
/// so the form layer stays trim- and Native-AOT-safe.
/// </summary>
[Generator]
public sealed class FormModelGenerator : IIncrementalGenerator
{
    private const string ModelAttribute = "BlazorDX.Primitives.Forms.DxFormModelAttribute";
    private const string Ns = "global::BlazorDX.Primitives.Forms";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<FormModelDef> models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ModelAttribute,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) =>
                    FormModelAnalysis.Build((INamedTypeSymbol)ctx.TargetSymbol, ctx.Attributes[0]));

        context.RegisterSourceOutput(models, static (production, model) =>
            production.AddSource($"{model.TypeName}FormModel.g.cs", Emit(model)));
    }

    private static SourceText Emit(FormModelDef model)
    {
        StringBuilder s = new();
        s.AppendLine("// <auto-generated/> by BlazorDX.SourceGen");
        s.AppendLine("#nullable enable");
        s.AppendLine();
        if (model.Namespace is not null)
        {
            s.AppendLine($"namespace {model.Namespace};");
            s.AppendLine();
        }

        string name = $"{model.TypeName}FormModel";
        s.AppendLine($"{model.Accessibility} sealed class {name} : {Ns}.IFormModel<{model.TypeName}>");
        s.AppendLine("{");

        EmitTool(s, model);
        EmitFields(s, model);
        EmitGetString(s, model);
        EmitSetString(s, model);
        EmitValidate(s, model);

        s.AppendLine("}");
        return SourceText.From(s.ToString(), Encoding.UTF8);
    }

    private static void EmitTool(StringBuilder s, FormModelDef model)
    {
        s.AppendLine($"    public string ToolName => {Literal(model.ToolName)};");
        s.AppendLine($"    public string? ToolDescription => {Literal(model.ToolDescription)};");
        s.AppendLine();
    }

    private static void EmitFields(StringBuilder s, FormModelDef model)
    {
        s.AppendLine($"    private static readonly {Ns}.FormFieldInfo[] _fields = new {Ns}.FormFieldInfo[]");
        s.AppendLine("    {");
        foreach (FormFieldDef f in model.Fields)
        {
            string choices = f.Choices.IsDefaultOrEmpty
                ? "null"
                : "new string[] { " + string.Join(", ", f.Choices.Select(Literal)) + " }";
            s.AppendLine(
                $"        new {Ns}.FormFieldInfo({Literal(f.PropertyName)}, {Literal(f.Label)}, {Literal(f.Description)}, " +
                $"{Ns}.FormFieldKind.{f.Kind}, {Bool(f.Required)}, {NDouble(f.Min)}, {NDouble(f.Max)}, " +
                $"{NInt(f.MaxLength)}, {Literal(f.Pattern)}, {Literal(f.Placeholder)}, {choices}),");
        }

        s.AppendLine("    };");
        s.AppendLine();
        s.AppendLine($"    public global::System.Collections.Generic.IReadOnlyList<{Ns}.FormFieldInfo> Fields => _fields;");
        s.AppendLine();
    }

    private static void EmitGetString(StringBuilder s, FormModelDef model)
    {
        s.AppendLine($"    public string GetString({model.TypeName} model, string field) => field switch");
        s.AppendLine("    {");
        foreach (FormFieldDef f in model.Fields)
        {
            if (f.Kind == "Date")
            {
                // ISO yyyy-MM-dd so the value binds straight into a native date input.
                string body = f.IsNullableValue
                    ? $"(model.{f.PropertyName} is {{}} __d_{f.PropertyName} ? __d_{f.PropertyName}.ToString(\"yyyy-MM-dd\", global::System.Globalization.CultureInfo.InvariantCulture) : string.Empty)"
                    : $"model.{f.PropertyName}.ToString(\"yyyy-MM-dd\", global::System.Globalization.CultureInfo.InvariantCulture)";
                s.AppendLine($"        {Literal(f.PropertyName)} => {body},");
                continue;
            }

            s.AppendLine(
                $"        {Literal(f.PropertyName)} => global::System.Convert.ToString(model.{f.PropertyName}, " +
                "global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty,");
        }

        s.AppendLine("        _ => string.Empty,");
        s.AppendLine("    };");
        s.AppendLine();
    }

    private static void EmitSetString(StringBuilder s, FormModelDef model)
    {
        s.AppendLine($"    public void SetString({model.TypeName} model, string field, string value)");
        s.AppendLine("    {");
        s.AppendLine("        switch (field)");
        s.AppendLine("        {");
        foreach (FormFieldDef f in model.Fields)
        {
            s.AppendLine($"            case {Literal(f.PropertyName)}:");
            s.Append(SetBody(f));
            s.AppendLine("                break;");
        }

        s.AppendLine("            default: break;");
        s.AppendLine("        }");
        s.AppendLine("    }");
        s.AppendLine();
    }

    private static string SetBody(FormFieldDef f)
    {
        string v = "__v_" + f.PropertyName;
        if (f.IsString)
        {
            return $"                model.{f.PropertyName} = value;\n";
        }

        return f.Kind switch
        {
            "Bool" =>
                $"                if (global::System.Boolean.TryParse(value, out var {v})) model.{f.PropertyName} = {v};\n",
            "Integer" or "Number" =>
                $"                if ({f.UnderlyingFqn}.TryParse(value, global::System.Globalization.NumberStyles.Any, " +
                $"global::System.Globalization.CultureInfo.InvariantCulture, out var {v})) model.{f.PropertyName} = {v};\n",
            "Date" =>
                $"                if ({f.UnderlyingFqn}.TryParse(value, global::System.Globalization.CultureInfo.InvariantCulture, " +
                $"global::System.Globalization.DateTimeStyles.None, out var {v})) model.{f.PropertyName} = {v};\n",
            "Enum" =>
                $"                if (global::System.Enum.TryParse<{f.UnderlyingFqn}>(value, true, out var {v})) model.{f.PropertyName} = {v};\n",
            _ =>
                $"                model.{f.PropertyName} = value;\n",
        };
    }

    private static void EmitValidate(StringBuilder s, FormModelDef model)
    {
        s.AppendLine(
            $"    public global::System.Collections.Generic.IReadOnlyList<{Ns}.FormValidationError> Validate({model.TypeName} model)");
        s.AppendLine("    {");
        s.AppendLine($"        var errors = new global::System.Collections.Generic.List<{Ns}.FormValidationError>();");
        foreach (FormFieldDef f in model.Fields)
        {
            EmitFieldChecks(s, f);
        }

        if (model.Validatable)
        {
            // The model implements IValidatableObject: run its cross-field validation too,
            // mapping each ValidationResult to a per-field (or form-level) error.
            s.AppendLine(
                "        var __ctx = new global::System.ComponentModel.DataAnnotations.ValidationContext(model);");
            s.AppendLine(
                "        foreach (var __vr in ((global::System.ComponentModel.DataAnnotations.IValidatableObject)model).Validate(__ctx))");
            s.AppendLine("        {");
            s.AppendLine("            string __member = string.Empty;");
            s.AppendLine("            foreach (var __n in __vr.MemberNames) { __member = __n; break; }");
            s.AppendLine(
                $"            errors.Add(new {Ns}.FormValidationError(__member, __vr.ErrorMessage ?? string.Empty));");
            s.AppendLine("        }");
        }

        s.AppendLine("        return errors;");
        s.AppendLine("    }");
    }

    private static void EmitFieldChecks(StringBuilder s, FormFieldDef f)
    {
        string prop = $"model.{f.PropertyName}";
        string err(string msg) => $"            errors.Add(new {Ns}.FormValidationError({Literal(f.PropertyName)}, {Literal(msg)}));";

        if (f.Required)
        {
            if (f.IsString)
            {
                s.AppendLine($"        if (string.IsNullOrWhiteSpace({prop}))");
                s.AppendLine(err($"{f.Label} is required."));
            }
            else if (f.IsNullableValue)
            {
                s.AppendLine($"        if (!{prop}.HasValue)");
                s.AppendLine(err($"{f.Label} is required."));
            }
        }

        if (f.MaxLength is { } maxLen && f.IsString)
        {
            s.AppendLine($"        if ({prop} != null && {prop}.Length > {maxLen})");
            s.AppendLine(err($"{f.Label} must be {maxLen} characters or fewer."));
        }

        if (!string.IsNullOrEmpty(f.Pattern) && f.IsString)
        {
            s.AppendLine(
                $"        if (!string.IsNullOrEmpty({prop}) && !global::System.Text.RegularExpressions.Regex.IsMatch({prop}, {Literal(f.Pattern)}))");
            s.AppendLine(err($"{f.Label} is not in the expected format."));
        }

        if (f.Kind is "Integer" or "Number")
        {
            string access = f.IsNullableValue ? $"{prop}.Value" : prop;
            string guard = f.IsNullableValue ? $"{prop}.HasValue && " : string.Empty;
            if (f.Min is { } min)
            {
                s.AppendLine($"        if ({guard}{access} < {Num(min)})");
                s.AppendLine(err($"{f.Label} must be at least {Trim(min)}."));
            }

            if (f.Max is { } max)
            {
                s.AppendLine($"        if ({guard}{access} > {Num(max)})");
                s.AppendLine(err($"{f.Label} must be at most {Trim(max)}."));
            }
        }
    }

    // ---- literal helpers ----

    private static string Literal(string? value) =>
        value is null ? "null" : SymbolDisplay.FormatLiteral(value, quote: true);

    private static string Bool(bool value) => value ? "true" : "false";

    private static string NDouble(double? value) =>
        value is { } d ? $"(double?){Num(d)}" : "(double?)null";

    private static string NInt(int? value) =>
        value is { } i ? $"(int?){i.ToString(CultureInfo.InvariantCulture)}" : "(int?)null";

    private static string Num(double value) =>
        value.ToString("R", CultureInfo.InvariantCulture);

    private static string Trim(double value) =>
        value.ToString("0.######", CultureInfo.InvariantCulture);
}
