using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BlazorDX.SourceGen;

/// <summary>
/// Emits a reflection-free <c>IGridRowAccessor&lt;TRow&gt;</c> implementation for
/// every type annotated with <c>[GridRow]</c>. Cell access becomes a generated
/// <c>switch</c>, so the grid binds data with zero runtime reflection and stays
/// safe under Native AOT and trimming.
/// </summary>
[Generator]
public sealed class GridAccessorGenerator : IIncrementalGenerator
{
    private const string RowAttribute = "BlazorDX.Primitives.Grid.GridRowAttribute";
    private const string AccessorNamespace = "global::BlazorDX.Primitives.Grid";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<GridRowModel> models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                RowAttribute,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) => GridRowAnalysis.Build((INamedTypeSymbol)ctx.TargetSymbol));

        context.RegisterSourceOutput(models, static (production, model) =>
            production.AddSource($"{model.TypeName}GridAccessor.g.cs", Emit(model)));
    }

    private static SourceText Emit(GridRowModel model)
    {
        StringBuilder source = new();
        source.AppendLine("// <auto-generated/> by BlazorDX.SourceGen");
        source.AppendLine("#nullable enable");
        source.AppendLine();

        bool hasNamespace = model.Namespace is not null;
        if (hasNamespace)
        {
            source.AppendLine($"namespace {model.Namespace};");
            source.AppendLine();
        }

        string accessorName = $"{model.TypeName}GridAccessor";
        source.AppendLine($"{model.Accessibility} sealed class {accessorName}");
        source.AppendLine($"    : {AccessorNamespace}.IGridRowAccessor<{model.TypeName}>");
        source.AppendLine("{");

        EmitColumns(source, model);
        EmitGetCellText(source, model);
        EmitGetCellValue(source, model);
        EmitCanEditColumn(source, model);
        EmitSetCellText(source, model);

        source.AppendLine("}");
        return SourceText.From(source.ToString(), Encoding.UTF8);
    }

    private static void EmitColumns(StringBuilder source, GridRowModel model)
    {
        source.AppendLine($"    private static readonly {AccessorNamespace}.GridColumnInfo[] _columns = new[]");
        source.AppendLine("    {");
        foreach (GridColumnModel column in model.Columns)
        {
            string isNumeric = column.IsNumeric ? "true" : "false";
            source.AppendLine(
                $"        new {AccessorNamespace}.GridColumnInfo(\"{column.Header}\", {column.Order}, {isNumeric}),");
        }

        source.AppendLine("    };");
        source.AppendLine();
        source.AppendLine(
            $"    public global::System.Collections.Generic.IReadOnlyList<{AccessorNamespace}.GridColumnInfo> Columns => _columns;");
        source.AppendLine();
    }

    private static void EmitGetCellText(StringBuilder source, GridRowModel model)
    {
        source.AppendLine($"    public string GetCellText({model.TypeName} row, int columnIndex) => columnIndex switch");
        source.AppendLine("    {");
        for (int index = 0; index < model.Columns.Length; index++)
        {
            string property = model.Columns[index].PropertyName;
            source.AppendLine(
                $"        {index} => global::System.Convert.ToString(row.{property}, global::System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty,");
        }

        source.AppendLine("        _ => string.Empty,");
        source.AppendLine("    };");
        source.AppendLine();
    }

    private static void EmitGetCellValue(StringBuilder source, GridRowModel model)
    {
        source.AppendLine($"    public double GetCellValue({model.TypeName} row, int columnIndex) => columnIndex switch");
        source.AppendLine("    {");
        for (int index = 0; index < model.Columns.Length; index++)
        {
            if (!model.Columns[index].IsNumeric)
            {
                continue;
            }

            string property = model.Columns[index].PropertyName;
            source.AppendLine(
                $"        {index} => global::System.Convert.ToDouble(row.{property}, global::System.Globalization.CultureInfo.InvariantCulture),");
        }

        source.AppendLine("        _ => double.NaN,");
        source.AppendLine("    };");
        source.AppendLine();
    }

    private static void EmitCanEditColumn(StringBuilder source, GridRowModel model)
    {
        source.AppendLine("    public bool CanEditColumn(int columnIndex) => columnIndex switch");
        source.AppendLine("    {");
        for (int index = 0; index < model.Columns.Length; index++)
        {
            GridColumnModel column = model.Columns[index];
            if (column.Editable && (column.IsString || column.IsNumeric))
            {
                source.AppendLine($"        {index} => true,");
            }
        }

        source.AppendLine("        _ => false,");
        source.AppendLine("    };");
        source.AppendLine();
    }

    private static void EmitSetCellText(StringBuilder source, GridRowModel model)
    {
        source.AppendLine($"    public void SetCellText({model.TypeName} row, int columnIndex, string value)");
        source.AppendLine("    {");
        source.AppendLine("        switch (columnIndex)");
        source.AppendLine("        {");
        for (int index = 0; index < model.Columns.Length; index++)
        {
            GridColumnModel column = model.Columns[index];
            if (!column.Editable)
            {
                continue;
            }

            if (column.IsString)
            {
                source.AppendLine($"            case {index}: row.{column.PropertyName} = value; break;");
            }
            else if (column.IsNumeric)
            {
                // Typed, invariant-culture parse; reject (leave unchanged) on bad input.
                source.AppendLine($"            case {index}:");
                source.AppendLine(
                    $"                if ({column.ParseTypeFqn}.TryParse(value, "
                    + "global::System.Globalization.NumberStyles.Any, "
                    + "global::System.Globalization.CultureInfo.InvariantCulture, out var __v" + index + "))");
                source.AppendLine($"                    row.{column.PropertyName} = __v{index};");
                source.AppendLine("                break;");
            }
        }

        source.AppendLine("            default: break;");
        source.AppendLine("        }");
        source.AppendLine("    }");
    }
}
